### ISSUE TITLE
Garmin auth failed in docker after a few hours

### ISSUE THREAD

**Issue by fform** [philosowaffle/peloton-to-garmin#101]
I get this log output

```
INFO:peloton-to-garmin:Uploading activites to Garmin...
[CRITICAL] Login Failure: Authentification failed
```

When I launch the docker container, it works fine. Fetches my number of activities `6` and uploads them to Garmin.

I haven't timed it exactly but it seems like the original auth to garmin times out at some point, and eventually the python script finds a new workout from Peloton to upload, but by that point the auth token is expired.

I have it setup in a docker container on my NAS to just run and check for updates every 10 minutes. It seems like the auth to garmin connect happens when the script runs initially, but what if you authed right before upload each time and then destroyed the garminUploader instance until you next need to upload?

**Comment by philosowaffle** [comment]
We re-authenticate with Garmin once every sync. So if your sync interval is set to 10min, then we are re-authenticating to Garmin once every 10min.

My gut tells me you are getting rated limited by Garmin, they have fairly aggressive limits around authentication.

 Try setting the sync interval to once an hour and see if the issue persists.

**Comment by fform** [comment]
Ok I will increase that and report back.

**Comment by fform** [comment]
Wanted to confirm that setting the timeout to 1 hour (3600 seconds) fixes this problem.

Maybe it's worth adding a minimum value to this as setting it lower breaks things?
