### ISSUE TITLE
dotnet build fails on MacOS (11.2)

### ISSUE THREAD

**Issue by johnmaconline** [philosowaffle/peloton-to-garmin#120]
Here is the `dotnet restore` command:

`$ dotnet restore

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
  Restoring packages for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Common/Common.csproj...
  Restoring packages for /Users/johnmacdonald/code/other/peloton-to-garmin/UnitTests/UnitTests.csproj...
  Restoring packages for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Garmin/Garmin.csproj...
  Restoring packages for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Peloton/Peloton.csproj...
  Restoring packages for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Conversion/Conversion.csproj...
  Restoring packages for /Users/johnmacdonald/code/other/peloton-to-garmin/src/PelotonToGarminConsole/PelotonToGarminConsole.csproj...
  Installing System.Threading.Tasks.Extensions 4.5.0.
  Installing System.Numerics.Vectors 4.4.0.
  Installing Microsoft.AspNetCore.Connections.Abstractions 2.1.3.
  Installing System.Buffers 4.4.0.
  Installing System.Memory 4.5.0.
  Installing Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions 2.1.3.
  Installing Microsoft.Extensions.Configuration.Abstractions 2.1.0.
  Installing System.Runtime.CompilerServices.Unsafe 5.0.0.
  Installing Microsoft.Extensions.Configuration 2.1.0.
  Installing Microsoft.Extensions.Primitives 2.1.0.
  Installing Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets 2.1.3.
  Installing Microsoft.AspNetCore.Server.Kestrel.Core 2.1.3.
  Installing System.IO.Pipelines 4.5.3.
  Installing System.Security.Principal.Windows 4.5.1.
  Installing System.Memory 4.5.2.
  Installing Microsoft.Extensions.Options.ConfigurationExtensions 2.1.0.
  Installing prometheus-net 4.1.1.
  Installing Flurl.Http 3.2.0.
  Installing JsonFlatFileDataStore 2.2.2.
  Installing Serilog 2.10.1-dev-01285.
  Installing System.Text.Json 6.0.0-preview.3.21201.4.
  Installing OpenTelemetry.Exporter.Jaeger 1.1.0-beta2.
  Installing OpenTelemetry.Instrumentation.Http 1.0.0-rc4.
  Installing prometheus-net.AspNetCore 4.1.1.
  Installing Flurl 3.0.2.
  Installing System.Diagnostics.DiagnosticSource 5.0.1.
  Installing Microsoft.Extensions.Configuration.Binder 2.1.0.
  Installing Newtonsoft.Json 12.0.2.
  Installing Microsoft.Extensions.Options 2.1.0.
  Installing Newtonsoft.Json 12.0.1.
  Installing Microsoft.Extensions.Logging.Abstractions 2.1.0.
  Installing Microsoft.Extensions.DependencyInjection.Abstractions 2.1.0.
  Installing Microsoft.AspNetCore.Server.Kestrel 2.1.3.
  Installing Microsoft.AspNetCore.Server.Kestrel.Https 2.1.3.
  Installing Microsoft.AspNetCore.Server.IISIntegration 2.1.7.
  Installing Microsoft.Extensions.Logging.Configuration 2.1.0.
  Installing OpenTelemetry.Api 1.1.0-beta2.
  Installing Microsoft.Extensions.Logging 2.1.0.
  Installing System.Reflection.Emit.Lightweight 4.7.0.
  Installing System.Collections.Immutable 1.4.0.
  Installing System.Buffers 4.5.1.
  Installing Microsoft.Bcl.AsyncInterfaces 6.0.0-preview.3.21201.4.
  Installing System.Threading.Tasks.Extensions 4.5.4.
  Installing Microsoft.AspNetCore 2.1.7.
  Installing System.Runtime.CompilerServices.Unsafe 6.0.0-preview.3.21201.4.
  Installing System.Runtime.CompilerServices.Unsafe 4.5.2.
  Installing System.Text.Encodings.Web 6.0.0-preview.3.21201.4.
  Installing System.Memory 4.5.4.
  Installing Microsoft.Extensions.Configuration.Abstractions 3.1.9.
  Installing Microsoft.Extensions.Primitives 2.0.0.
  Installing System.Runtime.CompilerServices.Unsafe 4.7.1.
  Installing Microsoft.Extensions.Configuration 2.0.0.
  Installing System.Runtime.CompilerServices.Unsafe 4.4.0.
  Installing Microsoft.Extensions.Primitives 3.1.9.
  Installing OpenTelemetry 1.1.0-beta2.
  Installing System.Threading.Tasks.Extensions 4.5.3.
  Installing FluentAssertions 6.0.0-alpha0002.
  Installing Moq 4.16.1.
  Installing Serilog.Sinks.Console 4.0.0-dev-00839.
  Installing Serilog.Sinks.File 5.0.0-dev-00909.
  Installing Serilog.Enrichers.Span 1.2.0.
  Installing Serilog.Sinks.Seq 5.0.1.
  Installing Serilog.Settings.Configuration 3.2.0-dev-00269.
  Installing Microsoft.NET.Test.Sdk 16.10.0-release-20210330-02.
  Installing Castle.Core 4.4.0.
  Installing NUnit3TestAdapter 4.0.0-beta.2.
  Installing Serilog.Sinks.Grafana.Loki 5.1.3.
  Installing Serilog.Sinks.Elasticsearch 8.5.0-alpha0003.
  Installing Serilog.Formatting.Compact 1.1.0.
  Installing Moq.AutoMock 2.3.0.
  Installing Serilog.Sinks.PeriodicBatching 2.3.0.
  Installing NUnit 3.13.2.
  Installing System.Runtime.CompilerServices.Unsafe 4.5.3.
  Installing Microsoft.Extensions.DependencyModel 3.0.0.
  Installing Microsoft.Extensions.Options.ConfigurationExtensions 2.0.0.
  Installing System.Text.Json 5.0.2.
  Installing Serilog.Sinks.Http 7.2.0.
  Installing Serilog.Formatting.Elasticsearch 8.5.0-alpha0003.
  Installing Serilog.Formatting.Compact 1.0.0.
  Installing Serilog.Sinks.PeriodicBatching 2.1.1.
  Installing System.Diagnostics.DiagnosticSource 4.5.1.
  Installing Elasticsearch.Net 7.8.1.
  Installing Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0.
  Installing Microsoft.CodeCoverage 16.10.0-release-20210330-02.
  Installing Microsoft.Extensions.Configuration.Binder 2.0.0.
  Installing Microsoft.Extensions.Options 2.0.0.
  Installing Microsoft.CSharp 4.6.0.
  Installing Microsoft.Extensions.Configuration.Abstractions 2.0.0.
  Installing Microsoft.Bcl.AsyncInterfaces 5.0.0.
  Installing System.Text.Encodings.Web 5.0.1.
  Installing Serilog.Sinks.RollingFile 3.3.0.
  Installing Microsoft.Extensions.Configuration 3.1.9.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/Conversion/obj/Conversion.csproj.nuget.g.props.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/UnitTests/obj/UnitTests.csproj.nuget.g.props.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/Common/obj/Common.csproj.nuget.g.props.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/PelotonToGarminConsole/obj/PelotonToGarminConsole.csproj.nuget.g.props.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/Garmin/obj/Garmin.csproj.nuget.g.props.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/Peloton/obj/Peloton.csproj.nuget.g.props.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/Common/obj/Common.csproj.nuget.g.targets.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/Garmin/obj/Garmin.csproj.nuget.g.targets.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/Peloton/obj/Peloton.csproj.nuget.g.targets.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/Conversion/obj/Conversion.csproj.nuget.g.targets.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/src/PelotonToGarminConsole/obj/PelotonToGarminConsole.csproj.nuget.g.targets.
  Generating MSBuild file /Users/johnmacdonald/code/other/peloton-to-garmin/UnitTests/obj/UnitTests.csproj.nuget.g.targets.
  Restore completed in 3.34 sec for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Conversion/Conversion.csproj.
  Restore completed in 3.34 sec for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Common/Common.csproj.
  Restore completed in 3.34 sec for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Peloton/Peloton.csproj.
  Restore completed in 3.34 sec for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Garmin/Garmin.csproj.
  Restore completed in 3.34 sec for /Users/johnmacdonald/code/other/peloton-to-garmin/UnitTests/UnitTests.csproj.
  Restore completed in 3.34 sec for /Users/johnmacdonald/code/other/peloton-to-garmin/src/PelotonToGarminConsole/PelotonToGarminConsole.csproj.`

Here is the `dotnet build` command:

`$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 58.16 ms for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Peloton/Peloton.csproj.
  Restore completed in 58.16 ms for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Garmin/Garmin.csproj.
  Restore completed in 58.16 ms for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Conversion/Conversion.csproj.
  Restore completed in 58.16 ms for /Users/johnmacdonald/code/other/peloton-to-garmin/src/PelotonToGarminConsole/PelotonToGarminConsole.csproj.
  Restore completed in 58.16 ms for /Users/johnmacdonald/code/other/peloton-to-garmin/UnitTests/UnitTests.csproj.
  Restore completed in 58.17 ms for /Users/johnmacdonald/code/other/peloton-to-garmin/src/Common/Common.csproj.
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/UnitTests/UnitTests.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/Common/Common.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/Peloton/Peloton.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/Conversion/Conversion.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/Garmin/Garmin.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/PelotonToGarminConsole/PelotonToGarminConsole.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/UnitTests/UnitTests.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/Common/Common.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/Peloton/Peloton.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/Conversion/Conversion.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/Garmin/Garmin.csproj]
/usr/local/share/dotnet/sdk/2.1.505/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/johnmacdonald/code/other/peloton-to-garmin/src/PelotonToGarminConsole/PelotonToGarminConsole.csproj]
    0 Warning(s)
    6 Error(s)

Time Elapsed 00:00:01.22`

**Comment by johnmaconline** [comment]
But then, after some snooping around, I found how to install the DOTNET SDK for macos, and that fixed the build issue.

Please add the SDK download and install to the macos instructions.  I assume Linux will be the same.

**Comment by johnmaconline** [comment]
One other little one...

The command line to execute is:

`dotnet run --project ./src/PelotonToGarminConsole/PelotonToGarminConsole.csproj`

**Comment by philosowaffle** [comment]
Thank you for this! I don't have a mac, or a clean system to test fresh installs on, so this is really helpful for catching my documentation errors.  The docs have now been updated.

**Comment by johnmaconline** [comment]
@philosowaffle Happy to help.  Thanks for driving this project
