### ISSUE TITLE
Local Time In Garmin is Always New York time

### ISSUE THREAD

**Issue by joelpeddie** [philosowaffle/peloton-to-garmin#133]
I live in the UK, when Peloton uploads my activities to Strava the time is correct: https://www.strava.com/activities/5551369530 06:33 on Wednesday, 30 June 2021
However when this is sent to Garmin the time is converted to New York time and displays as 00:33. 
I've tried to have a look at the code but I am a Java developer so not set up for C# coding. 

As the time displays correctly in Strava my guess is that the download from Strava gets the time in UTC, but then drops the timezone information, so when it goes in to Garmin it sees 00:33 but assumes local time (in my case GMT)

Not sure what the best fix is for this? Does the Strava download contain timezone? Should timezone be added as a config property then converted from UTC for upload to Garmin?

**Comment by philosowaffle** [comment]
Can you please fill out the issue template section:

Installation:

OS: [mac, linux, windows]
Method: [source, exe, docker]
Version: [1.2.0, 2.0.1, etc.]

**Comment by joelpeddie** [comment]
OS: mac
Method: docker
Version: docker

**Comment by philosowaffle** [comment]
Are you [setting your timezone](https://github.com/philosowaffle/peloton-to-garmin/blob/master/docker-compose.yaml#L8) in the docker container?
