### ISSUE TITLE
Error: 404 Not Found

### ISSUE THREAD

**Issue by Novelus23** [philosowaffle/peloton-to-garmin#136]
**Describe the bug**
Error occurs when attempting to download FIT files, error message: 
<h1>Error: 404 Not Found</h1>
            <p>Sorry, the requested URL <tt>&#039;https://api.onepeloton.com/api/workout/XXXX(replaced code for privacy)/summary&#039;</tt>
               caused an error:</p>
            <pre>Not found: &#039;/workout/XXXX(replaced code for privacy/summary&#039;</pre>

**To Reproduce**
1. Attempt to use Windows version 2, error occurs each time.

**Expected behavior**

**Logs**
``
[19:36:40 ERR] Http Call Failed. NotFound
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 404 Not Found</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 404 Not Found</h1>
            <p>Sorry, the requested URL <tt>&#039;https://api.onepeloton.com/api/workout/Xxxxx/summary&#039;</tt>
               caused an error:</p>
            <pre>Not found: &#039;/workout/Xxxxx/summary&#039;</pre>
        </body>
    </html>
`
[19:36:40 FTL] Uncaught Exception.
Flurl.Http.FlurlHttpException: Call failed with status code 404 (Not Found): GET https://api.onepeloton.com/api/workout/Xxxxxxx/summary
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at Peloton.PelotonService.DownloadLatestWorkoutDataAsync() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Peloton\PelotonService.cs:line 80
   at PelotonToGarminConsole.Program.RunAsync(Configuration config)
   at PelotonToGarminConsole.Program.Main(String[] args)
```

**Installation (please complete the following information):**
 - OS: [mac, linux, windows]
 - Method: [source, exe, docker]
 - Version: [1.2.0, 2.0.1, dockerTag, etc]

**Additional context**
Add any other context about the problem here.

**Comment by iggbom** [comment]
I get the same on MacOS using `philosowaffle/peloton-to-garmin:latest` docker image that was pulled a few minutes ago.


```
p2g  | Peloton To Garmin
p2g  | [17:56:14 WRN] App.PythonAndGuploadInstalledLocally setting is deprecated and will be removed in a future release. Please swith to using Garmin.UploadStrategy config.
p2g  | [17:56:23 ERR] Http Call Failed. NotFound 
p2g  |     <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
p2g  |     <html>
p2g  |         <head>
p2g  |             <title>Error: 404 Not Found</title>
p2g  |             <style type="text/css">
p2g  |               html {background-color: #eee; font-family: sans;}
p2g  |               body {background-color: #fff; border: 1px solid #ddd;
p2g  |                     padding: 15px; margin: 15px;}
p2g  |               pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
p2g  |             </style>
p2g  |         </head>
p2g  |         <body>
p2g  |             <h1>Error: 404 Not Found</h1>
p2g  |             <p>Sorry, the requested URL <tt>&#039;https://api.onepeloton.com/api/workout/<workout_id>/summary&#039;</tt>
p2g  |                caused an error:</p>
p2g  |             <pre>Not found: &#039;/workout/<workout_id>/summary&#039;</pre>
p2g  |         </body>
p2g  |     </html>
p2g  | 
p2g  | [17:56:23 FTL] Uncaught Exception.
p2g  | Flurl.Http.FlurlHttpException: Call failed with status code 404 (Not Found): GET https://api.onepeloton.com/api/workout/<workout_id>/summary
p2g  |    at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
p2g  |    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
p2g  |    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
p2g  |    at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
p2g  |    at Peloton.PelotonService.DownloadLatestWorkoutDataAsync() in /build/src/Peloton/PelotonService.cs:line 80
p2g  |    at PelotonToGarminConsole.Program.RunAsync(Configuration config)
p2g  |    at PelotonToGarminConsole.Program.Main(String[] args)
p2g exited with code 0
```

**Comment by philosowaffle** [comment]
Looks like Peloton killed off one of the API endpoints we were using to get data. Looks like I can get the same data from other sources.  

Fix has been merged to master, will cut a new release soon.

**Comment by philosowaffle** [comment]
https://github.com/philosowaffle/peloton-to-garmin/releases/tag/v2.0.3
