### ISSUE TITLE
Tool downloads in progress workouts

### ISSUE THREAD

**Issue by jyc66** [philosowaffle/peloton-to-garmin#14]
I have a cron job set up and if it runs while I'm working out it will download the partial workout.  Is there some sort of flag to detect when the activity is finished?

**Comment by clipin** [comment]
>  Is there some sort of flag to detect when the activity is finished?

A flag is not set in the code, but exists in the API. We're already calling this endpoint  
`https://api.onepeloton.com/api/user/USER-ID-GOES-HERE/workouts?joins=ride&limit=10&page=0`

We can look at the first ([0]) array position in "data", where the first key is "status:", this returns `COMPLETE` for finished workouts or IN_PROGRESS if currently underway.
