### ISSUE TITLE
[FeatureRequest] Configure app to automatically exit on finish

### ISSUE THREAD

**Issue by kenlpeters** [philosowaffle/peloton-to-garmin#140]
Consider checking out the [discussion forum](https://github.com/philosowaffle/peloton-to-garmin/discussions) to get help from the community.  Or fill out this template to get help here.

**Problem**
A clear and concise description of your question/problem.

I would like the program to exit once uploading is finished.  I am calling it from a Apple Shortcut and I need it to exit to end the shortcut.  

**Logs if applicable**
You can set your [config](https://github.com/philosowaffle/peloton-to-garmin/blob/master/configuration.example.json#L50) to `"Debug"` to get more detailed logs.
```
Paste Log output here
```

**Installation (please complete the following information):**
 - OS: Linux
 - Method: source
 - Version: 2.0.X

**Additional context**

**Comment by philosowaffle** [comment]
**Requirements:**
1. Create a new setting TBD in the App Config section that enables this behavior
2. When enabled, the application should exit immediately upon completion instead of waiting for the user to close the window

**Comment by kenlpeters** [comment]
I figured out a workaround.

I have two SH files.

SH #1: runs the command
Dot net run --project /arc/PelotonToGarminConsole/PelotonToGarminConsole.csproj

SH #2: runs
./Sh#.SH & 
Sleep 30 
Exit

I then have my shortcut in iOS connect to my server and execute the SH #2.
