### ISSUE TITLE
Is there a way to read user settings?

### ISSUE THREAD

**Issue by anlesk** [philosowaffle/peloton-to-garmin#15]
If I switch to kilometers instead of miles, the result is going to be incorrect.

Is there a way to read the user settings before making the calculations?

**Comment by douglasawh** [comment]
This needs to be merge with issue 20 in some way (or 20 marked as a duplicate), or this one needs to be marked as a feature request (and 20 stays as a "bug"). I don't think I have access to make any of that happen though.

I agree 100% though, if we can get that date from the API, we should use it.

**Comment by philosowaffle** [comment]
For reference, the code that assumes Miles is [here](https://github.com/philosowaffle/peloton-to-garmin/blob/master/lib/tcx_builder.py#L24) and [here](https://github.com/philosowaffle/peloton-to-garmin/blob/master/lib/tcx_builder.py#L64). 

I would expect that we may already have the units of measure available in the data returned from the existing Peloton api calls, it just needs to be inspected prior to making these conversions.

**Comment by philosowaffle** [comment]
I need some sample data to fix this properly (sorry I don't have access to my bike right now).  I'm specifically looking for what the value of [this field](https://github.com/philosowaffle/peloton-to-garmin/blob/master/tests/data/peloton_workoutsamples_cycling.json#L1256) is when using kilometers.  Drag and dropping the log file into github worked well last time.
