### ISSUE TITLE
Outdoor Walking Workout Failed to Deserialize

### ISSUE THREAD

**Issue by amy26point2** [philosowaffle/peloton-to-garmin#154]
I noticed a workout from yesterday missing from my uploads. I found it in the json folder with the name workout_failed_to_derserialize_1.json. This is an outdoor walking workout. 

[workout_failed_to_deserialize_1.txt](https://github.com/philosowaffle/peloton-to-garmin/files/6917924/workout_failed_to_deserialize_1.txt)

**Installation (please complete the following information):**
 - OS: mac
 - Method: source
 - Version: 2.0.5

**Comment by philosowaffle** [comment]
https://github.com/philosowaffle/peloton-to-garmin/releases/tag/v2.0.6
