### ISSUE TITLE
Won't re-download a file that was deleted

### ISSUE THREAD

**Issue by matthewhargrove** [philosowaffle/peloton-to-garmin#170]
Two files that were downloaded were corrupted for sum reason.  So I deleted them off my computer and tried to rerun the program.  for some reason it I can't make it re-download them.  It just says it has nothing to do.  How do I make it re-download them?

**Comment by philosowaffle** [comment]
Delete the [syncHistory.json](https://github.com/philosowaffle/peloton-to-garmin/wiki/Configuration#app-config) file.  This file is a log of previous downloads, and P2G will skip syncing anything it finds in this file.
