### ISSUE TITLE
"Failed to deserialize workout from Peloton...." - Metric Max_Value is Null

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#179]
### Discussed in https://github.com/philosowaffle/peloton-to-garmin/discussions/178

<div type='discussions-op-text'>

<sup>Originally posted by **matthewhargrove** October 26, 2021</sup>
I have started seeing an error message that says:

"Failed to deserialize workout from Peloton.  You can find raw data from workout here: @filename"

The workout seems to be fine, the file is there, and it uploads to Training Peaks.  Should I just ignore or is there an issue I should address?

![Untitled](https://user-images.githubusercontent.com/87453278/138961450-13b361da-badf-4816-90bb-be51a5365374.png)

</div>

**Comment by philosowaffle** [comment]
Root cause, serialization blows up with Max_Value for a metric is Null. While this shouldn't ever happen, we can still guard against it in the case the Peloton is sending us bad data as seen above.

**Comment by M2ast** [comment]
Good day, just received this error on the windows executable P2G:

![image](https://user-images.githubusercontent.com/102571259/185221386-a2a524db-9140-4188-89fa-d7b5aa480fd1.png)

Keep up the great work!
