### ISSUE TITLE
Calories don't import

### ISSUE THREAD

**Issue by daytonbrown** [philosowaffle/peloton-to-garmin#2]
Looks like calories aren't importing.  It appears that Garmin won't import anything that isn't a whole number.  Using the converted at http://rodemybike.today/strava-to-garmin/ it truncates/rounds the calorie number.

[for-garmin.zip](https://github.com/philosowaffle/peloton-to-garmin/files/2800887/for-garmin.zip)

[1548625847-45 min Pro Cyclist Ride with Christian Vande Velde-2b6404a46f604306a6b08934f950f1a2.zip](https://github.com/philosowaffle/peloton-to-garmin/files/2800890/1548625847-45.min.Pro.Cyclist.Ride.with.Christian.Vande.Velde-2b6404a46f604306a6b08934f950f1a2.zip)

Thanks for the work.  This is great and exactly what I want.

**Comment by daytonbrown** [comment]
Not sure how to issue a pull request but I fixed it locally.  

Changed this line  calories.text = str(int(round(workoutSummary["calories"]))) in the tcx_builder.py file

**Comment by philosowaffle** [comment]
Thanks for the fix, I've updated the relevant code.
