### ISSUE TITLE
[Feature] VO2 Max Calculation

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#212]
**Is your feature request related to a problem? Please describe.**
Workouts uploaded via P2G do not seem to impact Cycling VO2 max on Garmin Connect. 

**Describe the solution you'd like**
 Some users would like to have this additional data point.

**Additional context**
#207 

[This article](https://sportcoaching.co.nz/how-does-garmin-calculate-vo2-max/) outlines an algorithm P2G could use to estimate VO2 max.

**Acceptance Criteria:**
* For all cycling activities
  * Change the default device used to be Tacx
  * Update the documentation to explain that Tacx is currently the only known device that will get you VO2 max on your P2G rides.
* For all other activity types, leave the default device as is
```
<Creator>
    <Name>TacxTrainingAppWin</Name>
    <UnitId>8675309</UnitId>
    <ProductID>20533</ProductID>
    <Version>
        <VersionMajor>1</VersionMajor>
        <VersionMinor>30</VersionMinor>
        <BuildMajor>0</BuildMajor>
        <BuildMinor>0</BuildMinor>
    </Version>
</Creator>
```

## Old - won't do

**Acceptance Criteria:**
1. Research feasibility before beginning

- [ ] Investigate algo in above article. See if it seems to produce reasonable results, and determine complexity of code to replicate this algo
- [ ] FIT SDK - determine how to set VO2 Max in the FIT file

2. The `Format.Cycling` config section should take 2 new optional parameters
    1. `bool CalculateVo2Max` default is `false`
    2. `int Weight` in kilograms (is there a way to look up this information on the fly?)
3. If `Format.Cycling.CalculateVo2Max` is `true`, then `Weight` must be provided
4. If `Format.Cycling.CalculateVo2Max` is `true` then P2G should attempt to calculate Vo2 max for any Cycling workout and set it in the FIT file.
5. Update documentation to explain the VO2 max setting and call out that it is a custom algorithm in P2G, not guaranteed to match exactly what Garmin would generate (i.e. use at your own risk)

**Comment by philosowaffle** [comment]
It's also possible that Cycling VO2 max will be calculated by Garmin Connect if the [Tacx device is used](https://github.com/philosowaffle/peloton-to-garmin/discussions/207#discussioncomment-2085107). This would be a better solution than trying to write/maintain a custom calculation in P2G.

Can also investigate this as an option. 

@danielsfrazier can you post on this thread if you find an example tacx/trainer road/zwift FIT file for me to look at?

**Comment by philosowaffle** [comment]
Did some preliminary investigation on how to set VO2 max in the FIT file using the SDK, and unfortunately did not find anything. Will continue to look, but getting a sample workout with VO2 data already in it would be the most helpful.

**Comment by danielsfrazier** [comment]
I've new unable to track down sample data but I'll keep trying. My circle
of athletes doesn't include people who use zwift, trainer road or zwift.
I'll try a few people on strava. I tried to reach out to DC rainmaker
because I know he uses all those but he had not yet responded.

Since using the Tacx device I've consistently been getting VO2. Please try
changing yours and see if you get the same so it's not a sample of one.

BTW is there any way to private message on github? I couldn't find your
email or any way to message you. If not, please drop me a line using github
name at Gmail.

Regards,
Dan

**Comment by philosowaffle** [comment]
I tested this on two different accounts.

1) My test account - this account does not have any real device associated with it. Because I don't have a device connected with this account I have no way to set certain settings like Max HR.  This matters because I observed that when switching to the Tacx device for p2g, I was **not** getting VO2 max calculations, and ultimately I think the lack of Max HR is the reason why, since Garmin clearly states in their docs that VO2 max is only calculated when you have spent 20min above 70% of Max HR.

2) My personal account - my everyday account fully configured with Max HR and the kitchen sink. When I switched to using the Tacx device on this account I did start getting cycling VO2 max calculations.

![brave_2022-02-15_07-37-28](https://user-images.githubusercontent.com/7275041/154073110-79a618b2-3634-472f-b8c4-b1fa0a52ab48.png)
![brave_2022-02-15_07-37-41](https://user-images.githubusercontent.com/7275041/154073116-32a7bd4e-2cfe-4770-88fd-0bcadadc2997.png)

**Comment by philosowaffle** [comment]
Since I still do not see a way to set VO2 max in the FIT file itself, I think it makes sense for me to change this ticket to be such that the default device used is the Tacx for Cycling activities.  And I will update the documentation to explain the benefits of using Tacx over a different device for your cycling activities.
