### ISSUE TITLE
Updating deviceInfo.xml does not update the device on Garmin Connect

### ISSUE THREAD

**Issue by konradcodes** [philosowaffle/peloton-to-garmin#224]
**Problem**
When creating the deviceInfo.xml with the new Instinct 2 Solar it does not seem to show correctly in Garmin Connect ( Instead always shows Forerunner 945)

**Installation (please complete the following information):**
 - OS: [mac]
 - Method: [docker]

**Additional context**

my deviceInfo.xml below (with fake unitId)

      <Creator>
        <Name>Instinct 2 Solar</Name>
        <UnitId>11111111111</UnitId>
        <ProductID>3888</ProductID>
        <Version>
          <VersionMajor>6</VersionMajor>
          <VersionMinor>12</VersionMinor>
          <BuildMajor>0</BuildMajor>
          <BuildMinor>0</BuildMinor>
        </Version>
      </Creator>

**Comment by jheizerita** [comment]
I noticed the same trying to use the config from #212

**Comment by jheizer** [comment]
I noticed the same trying to use the config from #212

**Comment by konradcodes** [comment]
Okey I solved it ✅ : The documentation does not state this from what I see but all you need to do is:
Mount the location of your deviceInfo inside your docker-compose.yaml so it know where to get it from. 

Now the updated docker-compose.yaml looks like this

version: '3.9'

services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin
    environment:
      - TZ=America/Chicago
    volumes:
      - ./configuration.local.json:/app/configuration.local.json
      - ./deviceInfo.xml:/app/deviceInfo.xml
      - ./output:/app/output
      - ./working:/app/working
