### ISSUE TITLE
Revisit integration with Tapiriik

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#25]
Long term, would be ideal to integrate with Tapiriik so this tool will be more accessible for most users and easily run as a hosted service.

https://github.com/cpfair/tapiriik

**Comment by clipin** [comment]
Agree. Note that Garmin upload is no longer available in Tapiriik. Garmin migrated to their new Health API last year, cutting off Tapiriik and many other services. The only consumer sync choice I’m aware of is https://github.com/La0/garmin-uploader

From Tapiriik.com
> Due to new limitations in Garmin Connect's API, tapiriik can no longer upload activities to your Garmin Connect account, download historical activities from before you connected to tapiriik, or detect private acitivites (all activities uploaded to your Garmin Connect account will be synchronized).

**Comment by philosowaffle** [comment]
Oh that's right, I forgot Tapiriik had to drop support for Garmin sync :(
