### ISSUE TITLE
Failed to download workouts from Peloton

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#304]
Good day, just received this error on the windows executable P2G:

![image](https://user-images.githubusercontent.com/102571259/185221386-a2a524db-9140-4188-89fa-d7b5aa480fd1.png)

Keep up the great work!

_Originally posted by @M2ast in https://github.com/philosowaffle/peloton-to-garmin/issues/179#issuecomment-1218384714_

**Comment by philosowaffle** [comment]
Hi @M2ast what version of the windows exe are you running?

**Comment by M2ast** [comment]
Hi @philosowaffle, I'm using the latest version of the app - 3.02.
I am, however using it on Windows 11 and am requesting a sizable number of  uploads. Oddly, when I request - say - 500 activities, it fails with the error but when I request a more random number, like 526, it will pull them down. This only works to a point a and all my requests in the 700 level have failed.

![image](https://user-images.githubusercontent.com/102571259/185403612-095f7ae9-7ffd-40e2-b499-35c3300ce3e8.png)

**Comment by philosowaffle** [comment]
Gotcha, fetching that many workouts at once opens up a couple different avenues of things that could go wrong.

If you look in `C:\P2G\output\json` there should be some files saved. Probably with a naming convention of `workout_failed_to_deserialize_3989793.json`.  Can you upload one of those files to this thread?  Recommend opening it up in a text editor first and making sure there is no personal information in the file, though I doubt there will be.

**Comment by philosowaffle** [comment]
Thank you!  I found an issue and made a fix. Can you give this latest version a spin and see if you hit any additional errors?

https://github.com/philosowaffle/peloton-to-garmin/actions/runs/2894843513

**Comment by M2ast** [comment]
Morning @philosowaffle, 

I downloaded the latest version and it's now getting further and recognizing the classes but there are still errors at the end. I've uploaded the log file for you to see:

[log20220820.txt](https://github.com/philosowaffle/peloton-to-garmin/files/9387249/log20220820.txt)
.

**Comment by philosowaffle** [comment]
Seems you're now hitting some kind of Authentication error from Garmin.

You can try two things:

1. Update your Garmin config section to use `UploadStrategy: 1`, [documented here](https://philosowaffle.github.io/peloton-to-garmin/configuration/json.html#garmin-config)
2. Then try re-running with fetching just a single workout and see if it uploads

If that still doesn't work:

1. Switch back to `UploadStrategy: 2` in your config
2. Change your logging to 'Verbose'
3. Re-run P2G fetching just a single workout
4. There should be a `log.txt` file that gets generated. Open it up in a text editor and remove any occurrences of your Peloton Email/Password and Garmin Email/Password. (should be able to just do a search in the file for these and delete them)
5. Upload the `logs.txt` file here. This may help me see why Garmin is unhappy

**Comment by M2ast** [comment]
Hi @philosowaffle,
I managed to upload my few rides this morning and they show up in Garmin Connect without changing over to upload strategy to 1.

Here is the file using upload strategy 2:

[log20220822.txt](https://github.com/philosowaffle/peloton-to-garmin/files/9396874/log20220822.txt)

**Comment by philosowaffle** [comment]
Ah, good! That log file looks as expected for a successful run.

**Comment by tomtom215** [comment]
Hello!

Just wanted to report I'm having the same issue using the latest p2g-api dockerhub release (running Unraid):

> Failed to deserialize workout from Peloton. You can find the raw data from the workout here: @FileName

Compose file:
`version: "3.9"
services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin:stable
    environment:
      - TZ=America/Chicago
    volumes:
      - ./configuration.local.json:/app/configuration.local.json
      - ./data:/app/data
      - ./output:/app/output`

**Comment by philosowaffle** [comment]
@tomtom215 The `latest` tag on DockerHub already has a fix for the issue you mentioned. I just haven't cut a new release yet.  I plan to make a new release this weekend after I fix one or two other open issues.

**Comment by M2ast** [comment]
Hi @philosowaffle , I apologize for not clarifying earlier - the latest release you had me try out resulted in errors when I tried to bulk import my rides:

> [log20220820.txt](https://github.com/philosowaffle/peloton-to-garmin/files/9387249/log20220820.txt) .

Don't know if this was included in your latest. 

Keep up the great work!

**Comment by philosowaffle** [comment]
In this log file from 8/22: https://github.com/philosowaffle/peloton-to-garmin/issues/304#issuecomment-1222789430 it looks like you were able to successfully upload to Garmin.

Have you tried doing another bulk upload since then?  I just want to rule out that the error on 8/20 wasn't just a temporary problem on Garmins end.

**Comment by M2ast** [comment]
Hi @philosowaffle  - it appears to have worked! Well done!

**Comment by tomtom215** [comment]
> @tomtom215 The `latest` tag on DockerHub already has a fix for the issue you mentioned. I just haven't cut a new release yet. I plan to make a new release this weekend after I fix one or two other open issues.

Just tried the newest release, everything is working again. You rock!
