### ISSUE TITLE
[Feature] ARM Images for Raspberry Pi

### ISSUE THREAD

**Issue by tomtom215** [philosowaffle/peloton-to-garmin#310]
**Is your feature request related to a problem? Please describe.**
Currently this cannot run on a raspberry pi

**Describe the solution you'd like**
Release ARM compatible docker images

**Additional context**
This seems like the perfect low resource type of app to just leave it running on a raspberry pi

**Comment by philosowaffle** [comment]
arm64 is already a supported image. Are you specifically looking for arm32?

**Comment by philosowaffle** [comment]
https://github.com/f2calv/multi-arch-container-dotnet

**Comment by tomtom215** [comment]
> https://github.com/f2calv/multi-arch-container-dotnet

Thank you for the Christmas present! 😁
