### ISSUE TITLE
Update Dockerfile

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#32]
Dockerfile has fallen behind, needs to be updated to handle the more recent config values this script now supports.  I am not setup to test or run docker, so seeking help from someone in the community to update and verify its working.

**Comment by Octopusprime83** [comment]
I can help I've already modified your script to run on docker. I've enabled it to receive the peloton email and pass, the Garmin email and pass and debug modes as environmental variables. I've also enabled it so that when debug mode = true it will do a single pass through the code, but when debug mode= false it rechecks for work outs every 10 min. I can send you what I have if you'd like.

**Comment by mhjansen79** [comment]
I'm using the most recent copy from hub.docker.com but run into the issue that the distance cycled is much higher then peloton records, which in turn means I have much higher average speeds than even the max speed. Any idea where this comes from and how to fix it?

**Comment by Octopusprime83** [comment]
Hello mhjansen79 could I have a copy of one of the output files from the docker program. I'm still waiting on the bike (next Tuesday) so I'm unable to replicate this issue myself on my end at the moment. Do you know if this data mismatch carries over go any other work out types (strength cardio etc?)

**Comment by philosowaffle** [comment]
The master branch is currently hardcoded to assume miles, so if you happen to be using metric units then the calculations will be off. I have an open PR #29 that resolves this issue but havent found anyone who could test and verify its working for me.  Might just merge it and hope for the best I guess.

**Comment by mhjansen79** [comment]
That's the issue. I use metric. How can I help you test if it works?

**Comment by philosowaffle** [comment]
Two ways to do this:

1) Checkout the feature branch and run it locally. See if the measurements look correct now.

OR

2) Send me a link to one of your Peloton workouts that uses metric units and I should be able to grab the data I need from there to verify the code works.

**Comment by Octopusprime83** [comment]
If this works I can wrap this into a docker for you and put it up on the docker repo.


@philosowaffle we should also update your documentation for the docker piece, as I've modified your script to run a little differently.

**Comment by mhjansen79** [comment]
@philosowaffle apoligies. it took me al ittle while to figure out how to get the file out of docker. (newb) Here's a link to workout from today: https://drive.google.com/file/d/1qA_lA62Jm9-hniJCXSEbrUgkcnPkDZ4F/view?usp=sharing

**Comment by philosowaffle** [comment]
@mhjansen79 I'm sorry I should have clarified, I need the original Peloton data to test that it gets converted correctly.  But, this should be much easier than pulling a file out of the docker container. You can just send me a link to the workout on OnePeloton like this:  https://members.onepeloton.com/profile/workouts/6a8b9725f87346b9a84c917c32a02df6

If your profile is private you may need to make it temporarily public so I can access the workout.

**Comment by mhjansen79** [comment]
Here's a link to the same workout: https://members.onepeloton.com/profile/workouts/2327cf5719004d7c8cd2c162b5a35ad5

**Comment by philosowaffle** [comment]
thanks!

**Comment by philosowaffle** [comment]
@mhjansen79 & @Octopusprime83 the KM fix has been merged to master and is in this release: https://github.com/philosowaffle/peloton-to-garmin/releases/tag/v0.0.5

**Comment by Octopusprime83** [comment]
@mhjansen78 @philosowaffle I'll be away from my desktop (where I have the files to work on this) until Wednesday, I plan to have this wrapped and pushed to the hub by the weekend.

**Comment by mhjansen79** [comment]
@Octopusprime83 Thanks for this. I've updated the docker image but now run into an issue where the script errors out. Here is the log:

![image](https://user-images.githubusercontent.com/24822406/92097389-50a60d80-edd8-11ea-86e1-e59eeb773bb5.png)

**Comment by Octopusprime83** [comment]
@mhjansen79 when setting up the container did you set "-e DEBUG=false"?

**Comment by mhjansen79** [comment]
That was indeed the issue. On the docker hub page I read that debug was set to false as a default. I've set it now and it runs correctly and the distance is also now correct. Thanks for your help on this!
