### ISSUE TITLE
[ERR] Failed to fetch recent workouts from Peleoton.

### ISSUE THREAD

**Issue by daytonbrown** [philosowaffle/peloton-to-garmin#320]
Failing to download latest workouts.  They are distance based ones.  (ex. https://members.onepeloton.com/profile/workouts/32cb1c294ccd4a5b8416c828b285f0f3)

Running the windows EXE version 3.0.2  Which worked yesterday.

Log is attached.
[log20220828.txt](https://github.com/philosowaffle/peloton-to-garmin/files/9440345/log20220828.txt)

Thanks again for the app.  You're doing the lords work for us exercise data nerds.

**Comment by philosowaffle** [comment]
Ah interesting, I haven't see the Distance based rides. I'll need to try one.

This should be fixed now on: https://github.com/philosowaffle/peloton-to-garmin/releases/tag/v3.0.3
