### ISSUE TITLE
Conversion incorrectly shifts workout time by time zone offset

### ISSUE THREAD

**Issue by adepue** [philosowaffle/peloton-to-garmin#357]
**Describe the bug**
Typically I do workouts from 5-7am Pacific time (currently UTC -7).  When the workouts are converted and inserted into Garmin, they are uploaded as 12-2pm instead.  
It seems like it is downloading them as absolute time with timezone notation, but dropping the timezone notation and uploading to garmin as my "default timezone" some how.  GIven the time shift is exactly 7 hours consistently, the timezone information seems to be mis-converted consistently

**To Reproduce**
1) Do workout at X time in PDT (UTC - 7).
2) Run sync workflow via GH action.
3) Check workout uploaded to Garmin at X time + 7 hours instead.

**Expected behavior**
Times on workouts match when they actually happened.

**Logs**
```
Paste Log output here
```

**Installation (please complete the following information):**
 - OS: [mac, linux, windows]
 - Method: [source, exe, docker]
 - Version: [1.2.0, 2.0.1, dockerTag, etc]

**Additional context**

**Comment by philosowaffle** [comment]
I believe providing your timezone information via [env variable](https://github.com/adepue/peloton-to-garmin/blob/master/.github/workflows/sync_peloton_to_garmin.yml#L84) to the docker container should resolve this.

Example: https://github.com/philosowaffle/peloton-to-garmin/discussions/303

**Comment by adepue** [comment]
That worked great thanks.  My thought was that the code might infer that from the workout downloaded time in the peloton feed, but maybe its not available.  Thanks!

**Comment by philosowaffle** [comment]
Yeah, unfortunately the endpoints I've explored so far do not give back the User's timezone information. But Peloton's API is regularly updated and I haven't explored all of it yet, so its possible the data is out there somewhere.
