### ISSUE TITLE
[Question] keep getting password reset email from Garmin

### ISSUE THREAD

**Issue by paulmorabito** [philosowaffle/peloton-to-garmin#359]
Hi,

I'm using the docker image with latest tag and everything is working well sync wise. Thank you so much for this. 

I'm not 100% sure this is related but I can't think of anything else it could be. I keep getting password reset emails from Garmin, every other day just about. I've seen other Garmin sync apps report similar and that's it's an anti bot or security measure from Garmin. I'm currently syncing every hour. 

Do you have any ideas on how we can avoid triggering this? Or could it be something else?

Thanks,

**Comment by philosowaffle** [comment]
This does sound like Garmin is flagging P2G as suspicious activity on your account and so forcing a password reset.

I'd definitely start with turning down the sync frequency, personally I have mine set to once per day and have not had any trouble.

If you're still getting flagged, you might try turning off auto-sync and go to just manually syncing workouts when needed.  There is now a [webui](https://philosowaffle.github.io/peloton-to-garmin/install/docker-webui.html) provided that makes it much easier to just do a quick sync from your phone or computer.

**Comment by paulmorabito** [comment]
I’ve changed it to every six hours and will continue to test. Will let you know how it goes. It might be worth adding a note to the docs regarding this so others don’t hit this also.

**Comment by philosowaffle** [comment]
This is actually already in the docs, you can find it in the [App Config](https://philosowaffle.github.io/peloton-to-garmin/configuration/json.html#app-config) section, under the Description for the `PollingIntervalSeconds` setting.

Although, I do see a typo, as the docs indicate the default value for this setting is 3600s (hourly) which is not correct, the default is actually 86400s (daily).  I'll fix that up now.

**Comment by paulmorabito** [comment]
Great, thanks. I missed that entirely!

Paul Morabito
