### ISSUE TITLE
Peloton Row workouts - aka "caesar" error

### ISSUE THREAD

**Issue by cpachris1969** [philosowaffle/peloton-to-garmin#370]
**Describe the bug**
The program was working well for me until my new Peloton Row came yesterday.  Now when I run the sync, the program fails 

**Logs**
```
Paste Log output here
[16:49:14 ERR] Http Failed to deserialize response to target type: JSON
Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: GET https://api.onepeloton.com/api/user/ac6b497fc71d48fbb853366ccfa5921f/workouts?limit=5&sort_by=-created&page=0&joins=ride
 ---> Newtonsoft.Json.JsonSerializationException: Error converting value "caesar" to type 'Common.Dto.Peloton.FitnessDiscipline'. Path 'data[0].fitness_discipline', line 1, position 116.
 ---> System.ArgumentException: Requested value 'caesar' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---

**Installation (please complete the following information):**
 - OS: [windows]
 - Method: [exe]
 - Version: [3.1.1]

**Additional context**
Fairly new to the program, so I don't know if it's a transient issue that will resolve itself, or if the new Peloton Row workouts have a different form.

**Comment by philosowaffle** [comment]
Congrats on the Rower! I believe you're one of the first to use P2G with the new Rowing machine and this does look like a problem with P2G.  

Errors like this are expected whenever new devices are released, there's a bit of a learning curve for me to figure out how Peloton is recording the data and then how to correctly map that into data Garmin understands.

But now that I have this sample workout I should be able to update P2G to handle it, though it may take me a few days to get a fix in.

**Comment by cpachris1969** [comment]
Thanks.   If there is anything from the log I can send you to assist, let
me know.   Appreciate your work on this project.

Chris

**Comment by philosowaffle** [comment]
If you're interested you can download a "work in progress" version [here](https://github.com/philosowaffle/peloton-to-garmin/suites/9662040098/artifacts/462294850). It has minimal support for Rowing and I believe should avoid the exception being thrown.

Right off the bat you'll notice there is **a lot** of data missing in this initial attempt (like avg pace). But from the raw data I can see that Peloton has captured a lot of cool metrics about the row, will try to get as much of it as possible over to Garmin as I continue to work on this.

![firefox_L5jYxNLayG](https://user-images.githubusercontent.com/7275041/205534423-4ab888e0-c511-466e-9d2a-72774f2f2fb3.png)

**Comment by cpachris1969** [comment]
You are earning more than a coffee, for sure.  Keep up the awesomeness!

**Comment by philosowaffle** [comment]
New build available:
* [Windows exe download](https://github.com/philosowaffle/peloton-to-garmin/suites/9685619393/artifacts/463856721)
* Docker tags
   *  `pr-validator-console-A`
   * `pr-validator-api-A`
   * `pr-validator-webui-A`

New things working:
* Stroke Rate Graph
* Pace Graph
* Roll up metrics (avg pace, best pace, etc)
* Total stroke count

Known remaining issues:
* laps don't look right
* Shows up on Garmin as `Rowing` even though I'm trying to specify `IndoorRowing`
* Think I can find a way to also calculate AvgStrokeDistance which Peloton does not expose, but Garmin supports

**Comment by cpachris1969** [comment]
The "laps don't look right" comment might not be necessary to fix.  Garmin is showing the "Strive Score segments", which from memory, correlated with the different segments of the class.   So not really laps....but kind of?  Love the quick response on this one. 

![image](https://user-images.githubusercontent.com/119820377/205789541-17223974-9428-453c-950e-cabc8ae29630.png)

**Comment by cpachris1969** [comment]
I've noticed that while the Row workouts are syncing....they are not being used in Garmin's Training Status metric.   More specifically, they do not show up in the Exercise Load component of Training Status.   They are missing entirely.

**Comment by hotbread613** [comment]
my apologies. I'm a newbie to Docker. It seems from the documentation in Docker that I cannot edit the container files, themselves. Docker tells me that Web-UI is downloading the "Stable" version from 6 weeks ago. Pulling the Headless version for "Latest" gives me a file that's 25 days old.

**Comment by philosowaffle** [comment]
To change which version of the container you wish to pull, you will modify the portion after the colon`:`

```
philosowaffle/peloton-to-garmin:api-stable
```

So if you are using the [WebUI compose](https://github.com/philosowaffle/peloton-to-garmin/blob/master/docker/webui/docker-compose-ui.yaml#L6) file then you will modify line 6 and 18.

```
philosowaffle/peloton-to-garmin:pr-validator-api-A
philosowaffle/peloton-to-garmin:pr-validator-webui-A
```

For headless it is:

```
philosowaffle/peloton-to-garmin:pr-validator-console-A
```

These tags are just temporary builds so folks can test things before I get them added to the normal `stable` tag.

**Comment by hotbread613** [comment]
Made the updates above to WebUI file

Ran the command line "docker-compose pull && docker-compose up -d" 
Pull completed with no errors

However, containers will not run successfully. There is an AMD64 icon next to each of the containers. Hovering over those icons shows the following error: "Image may have poor performance, or fail, if run via emulation"

**Comment by hotbread613** [comment]
Made updates to the above referenced Headless file

ran the command line "docker-compose pull && docker-compose up -d"
Pull initiated but not completed.
system returned the following error:

Running 1/2
 ⠿ Network p2g-headless_default  Created                                   0.0s
 ⠿ Container p2g                 Starting                                  0.3s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/host_mnt/Applications/p2g-headless/configuration.local.json" to rootfs at "/app/configuration.local.json": mount /host_mnt/Applications/p2g-headless/configuration.local.json:/app/configuration.local.json (via /proc/self/fd/14), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by philosowaffle** [comment]
> /host_mnt/Applications/p2g-headless/configuration.local.json

Double check that path exists and that the file can be Read and Written to

**Comment by hotbread613** [comment]
All three p2g containers are exiting immediately on run, and have the same error logs:

2022-12-08 09:35:43 Unhandled exception. System.IO.IOException: Function not implemented
2022-12-08 09:35:43    at System.IO.FileSystemWatcher.StartRaisingEvents()
2022-12-08 09:35:43    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
2022-12-08 09:35:43    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
2022-12-08 09:35:43    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
2022-12-08 09:35:43    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
2022-12-08 09:35:43    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
2022-12-08 09:35:43    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
2022-12-08 09:35:43    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
2022-12-08 09:35:43    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
2022-12-08 09:35:43    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
2022-12-08 09:35:43    at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
2022-12-08 09:35:43    at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
2022-12-08 09:35:43    at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
2022-12-08 09:35:43    at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
2022-12-08 09:35:43    at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
2022-12-08 09:35:43    at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
2022-12-08 09:35:43    at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
2022-12-08 09:35:43    at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
2022-12-08 09:35:43    at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
2022-12-08 09:35:43    at Program.<Main>$(String[] args) in /build/src/WebUI/Program.cs:line 22
2022-12-08 09:35:43    at Program.<Main>(String[] args)
2022-12-08 09:35:43 qemu: uncaught target signal 6 (Aborted) - core dumped
2022-12-08 09:35:43 Aborted

**Comment by hotbread613** [comment]
I think we're getting somewhere - at least in terms of those using newer Macbooks (featuring M1 chips). It seems that the issue lies in the emulation. The ARM64 is not currently supported by Docker [https://github.com/EventStore/EventStore/issues/2380]. 

It seems that there is work on an alpha version under way, and specific instructions for the docker file in order to get it to run correctly on the M1

**Comment by philosowaffle** [comment]
@hotbread613 lets move this troubleshooting over to the [Discussion forum](https://github.com/philosowaffle/peloton-to-garmin/discussions) so we can keep this Bug focused on Rower support.  Can start a fresh discussion and share your config/docker-compose files which may help.

**Comment by philosowaffle** [comment]
Been a few days, got really busy with my day job. But here's my plan:

1. This weekend, will take the current support and get it added to the main releases/tags, closing this ticket
2. Will create follow up tasks to address the remaining known issues
    1.  laps don't look right - missing things like Lap Avg HR, Lap Avg Stroke, etc.
    2. Shows up on Garmin as Rowing even though I'm trying to specify IndoorRowing
    3. Think I can find a way to also calculate AvgStrokeDistance which Peloton does not expose, but Garmin supports
    4. Investigate Row not being used for Garmin's Training Status

**Comment by philosowaffle** [comment]
> Investigate Row not being used for Garmin's Training Status

[This article](https://support.garmin.com/en-US/?faq=VxKazDQ2mkAmDoQbJriEBA) seems to say that only Running and Cycling activities count towards Training Status at this time, which is sad :(


1. Fix Laps - #374
2. AvgStrokeDistance - #381

**Comment by cpachris1969** [comment]
I think the comment in the linked article is dealing with what activities can generate a VO2 max, which is required for a training status.   But that's not the issue I'm having.  

Once you have a training status (I have one) there is an Exercise Load portion of the calculation which shows all activities (i.e., walking, general cardio, treadmill, etc....including other Peloton type activities that are synched, like stretching classes etc.).  However, the uploaded Row workouts are not showing up here at all.

**Comment by philosowaffle** [comment]
I see what you're saying after uploading to my personal account its not counting towards Acute Load.

Took another look and all the data is provided that would normally be used to calculate TE and Load, namely HR and Power.  On my account it looks like Garmin is calculating Intensity Factor and Training Stress Score for the Row so not sure why its not using that for the Training Status and Load graphs.

All that is to say, I have no theories on why its not counting towards Acute Load, will keep thinking on it though.

**Comment by cpachris1969** [comment]
As another test tonight, I used my Garmin epic watch to log my Peloton Row workout.  I chose 'Row Indoor' on my watch.   After the workout, I used P2G to sync the workout from Peloton, so now I have both workouts in Garmin connect.  Both are classified as 'Rowing'.  But only the version that was logged from my watch shows up in the Exercise Load portion of training status.  Not the same activity synced from Peloton.   

Would be more than happy to share TCX or other files from both if you think that generates any ideas.   Appreciate all your work on this program.

**Comment by philosowaffle** [comment]
Alright, made a dedicated ticket for investigating why the Row isn't counting towards Load.

And yes, it would be helpful to compare the original watch data against what P2G generated. Instead of exporting TCX, could you click `Export Original` and upload both of those workouts on the new issue linked below?

1. #383
