### ISSUE TITLE
[Feature] Rowing - Should count towards Training Status and Acute Load

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#383]
Currently the Rowing workouts are not being counted towards Training Status, specifically they are not included in the Acute Load chart.

**Comment by cpachris1969** [comment]
Here the original workout exports for both that I mentioned.   

[from_peloton_P2G_upload.zip](https://github.com/philosowaffle/peloton-to-garmin/files/10202838/from_peloton_P2G_upload.zip)
[from_watch_epix_upload.zip](https://github.com/philosowaffle/peloton-to-garmin/files/10202839/from_watch_epix_upload.zip)

**Comment by philosowaffle** [comment]
Finally got around to taking a peek at these two files. Here's what I found so far. the Epix watch calculated these additional fields in the FIT file that I think are relevant:

```
TrainingLoadPeak::59.04991
TotalTrainingEffect::3.4
TotalAnaerobicTrainingEffect::0.2
```

I went and double checked an existing Cycle workout uploaded by P2G, one that counted towards Training Load for me, and confirmed the P2G Cycle workouts do not include the Training Fields the Epix captured above. So for some reason, when P2G uploads Cycling/Tread workouts, Connect is figuring out a way to count them towards Load, but is not doing the same for the Row workouts.

Will keep investigating/thinking on it.

**Comment by cpachris1969** [comment]
The Peloton Row workouts are now showing up for me in Training Status and Acute Load measurements.   Did you make a change?   Or did Garmin start handling it correctly?

**Comment by philosowaffle** [comment]
If you happened to grab the [latest](https://github.com/philosowaffle/peloton-to-garmin/suites/10032029557/artifacts/487777404) sometime this week, then there are the following changes related to Row, but I did not expect any of these changes to fix the missing TrainingStatus/Load.

[#381] Rowing - now captures AvgStrokeDistance
[#374] Rowing - can now configure PreferredLapType for Row workouts
Rowing - Uploaded activity device is now an Epix instead of the TACX

**Comment by cpachris1969** [comment]
I'm still on a version that shows a Forerunner 945 as the device.  TACX
shows for my cycle workouts....but never has for the row workouts.

i'll download the latest version and make sure it is working in that one
also.   I'm guessing it was  change on the Garmin side....but if it works
it works.

**Comment by philosowaffle** [comment]
Ah sorry, too early for my brain, got the TACX mixed up with the 945.  Definitely sounds like something changed on Garmin's side.  Glad its working!

**Comment by philosowaffle** [comment]
@cpachris1969 just checking in, are Rows still counting towards Training Status and Acute Load? If so I'll probably go ahead and close this ticket.

**Comment by cpachris1969** [comment]
Yes.  Everything working perfectly.  Appreciated.

**Comment by cagnulein** [comment]
Sorry to raise up this ticket. Is there a custom profile also for treadmills?
