### ISSUE TITLE
[Feature] Intensity Minutes

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#388]
### Discussed in https://github.com/philosowaffle/peloton-to-garmin/discussions/387

<div type='discussions-op-text'>

<sup>Originally posted by **CalebJRogers** December 11, 2022</sup>
Hello all,

First time user here as I just got my first Garmin watch. I was able to get everything installed easily via Docker - the detailed documentation made it so easy!

One thing I have noticed though is that my synced rides do not include "Intensity Minutes." I've attached a screenshot for reference. 

I've looked through all the settings/configuration (i'm running the webui version) and I don't "think" I've missed anything. I did not record the workout via my watch, or broadcast the heart rate - I used an external ANT+ heart rate monitor and just synced afterword. 

What is the best practice for making sure all the data is synced? I was planning on trying the watch as a heart rate broadcast next but wanted to check in here first to see what is suggested.

![IMG_0525](https://user-images.githubusercontent.com/53285077/206916781-2ae45869-eebb-43af-9832-9e1863ec4dfd.jpg)
</div>

**Comment by philosowaffle** [comment]
Intensity Minutes is something that is normally calculated by the watch so by default the Peloton data will not include Intensity Minute information.

Garmin seems to have documentation about what goes into [calculating intensity minutes](https://support.garmin.com/en-US/?faq=pNU9nnDzzGAHmEavp9rpY8), so theoretically P2G may be able to replicate what the Garmin watch is doing by measuring time in HR zones. But this would be a new feature.

Need to determine:

- [ ] How to calculate Intensity Minutes
- [ ] How to correctly set Intensity Minutes into the FIT file so Garmin honors it

**Comment by cpachris1969** [comment]
good article on intensity minutes:

https://support.garmin.com/en-US/?faq=pNU9nnDzzGAHmEavp9rpY8

**Comment by deagleD** [comment]
Hey! It seems that the intensity minutes are somehow calculated and replicated to garmin. I have a workout synced to garmin with 23 intensity minutes and another workout (today) with only 2 intensity minutes (in my opinion it was much more intense than 2 minutes :D).

Does Garmin do the calculation or PTG?

I'm doing my workouts with an external HRM+ synchronised with Peloton. I'm wearing my watch with no workout selected. 

23 Minutes:
![image](https://github.com/philosowaffle/peloton-to-garmin/assets/5553611/ebe67bc0-efbd-4586-9522-0035a8723507)

2 Minutes:
![image](https://github.com/philosowaffle/peloton-to-garmin/assets/5553611/fdbb4660-4655-4246-b87a-196c2b99a0c0)

**Comment by qpop01** [comment]
I wonder if this ever got anywhere? I have mostly been cycling outside over the Summer and got a bit obsessed with intensity minutes. It would be great to see P2G pushing the data to Garmin. 

My guess is that if Garmin was reading it from the exercise data it would be able to pick it up from the activity, as we're pushing through power/heart-rate/training effect already.

**Comment by philosowaffle** [comment]
Currently P2G does not do any calculations related to Intensity Minutes. P2G simply pushes all the raw metric data to Garmin and allows Garmin to decide what to do with that data.  This holds true for all of Garmin's proprietary fields such as Intensity Minutes, Training Effect, Training Stress Score, and VO2 Max.

**Comment by qpop01** [comment]
It's curious then that Connect picks up my 45 minute ride as 1 minute of vigorous effort!

Image below shows the ride. Do we have any clue what is missing for it to generate the "correct" output? Any information I could give to try and narrow it down?

![image](https://github.com/philosowaffle/peloton-to-garmin/assets/37111291/7f7568f4-7273-428f-960a-3864ea7b8a7a)

**Comment by philosowaffle** [comment]
Closing for now.  Currently thinking this falls in the same category as TE/TSS/VO2 calculations which are completely dictated by Garmin's convoluted rules.  Current recommendation would be to work within the rules outlined in [Garmin's documentation](https://support.garmin.com/en-US/?faq=pNU9nnDzzGAHmEavp9rpY8), and experiement with using different Devices via the new [UI configuration](https://github.com/philosowaffle/peloton-to-garmin/issues/606#issuecomment-1902690584) in P2G.
