### ISSUE TITLE
Correcting time of imported activity

### ISSUE THREAD

**Issue by manforrilla** [philosowaffle/peloton-to-garmin#389]
### Discussed in https://github.com/philosowaffle/peloton-to-garmin/discussions/378

<div type='discussions-op-text'>

<sup>Originally posted by **manforrilla** December  8, 2022</sup>
When I sync a workout that I started at 9pm it will upload to garmin as a completed activity the next day at 5am, so it is posting the activity 8 hrs ahead of actual time. Its not a big deal at all as it is very easy to fix this in editing the activity but wondering if there is an easy change that would correct this.

I tried adding this into the workflow file from reading another users comment on time 
      env:
       TZ: America/Los Angeles
But I must be doing this in the wrong location in my forked file.
</div>

**Comment by philosowaffle** [comment]
changes have been applied to main repo here as example for others in future
