### ISSUE TITLE
Using Github Actions not picking up Rows

### ISSUE THREAD

**Issue by hotbread613** [philosowaffle/peloton-to-garmin#393]
Running peloton-to-garmin from Github actions not picking up meditation or rowing.

**Comment by philosowaffle** [comment]
Support for row workouts has not made it into the `stable` tag yet (I still have some more testing to do on them). But they are available in the `latest` tag.

You can modify [line 20](https://github.com/hotbread613/peloton-to-garmin/blob/master/.github/workflows/sync_peloton_to_garmin.yml#L20) of your workflow file and replace `stable` with `latest`.

Regarding meditation, based on the output from [this run](https://github.com/hotbread613/peloton-to-garmin/actions/runs/3700450620/jobs/6268880905) it appears the Meditation workout was synced to Garmin.

```
[20:17:42 INF] Uploading to Garmin: /app/working/upload/508909ef40ac4076a09ec4c9f39bfc83_5_min_Meditation_for_Healing_with_Aditi_Shah.Fit
```
