### ISSUE TITLE
Support runs (or ignore in the API pull)

### ISSUE THREAD

**Issue by clipin** [philosowaffle/peloton-to-garmin#4]
Outdoor runs are exported as cycling activities. The metrics are off. Suggest a check for activity type, and ignore non-cycling for now. Nice to ultimately support all Peloton activities, but might require meaningful work.

In my spare time, I may tinker with supporting runs. Not a major personal priority at moment.

**Comment by philosowaffle** [comment]
@clipin - Do you happen to have a sample data set you'd be willing to upload? I don't have a Tread so I'm limited in what I can test or verify.

**Comment by clipin** [comment]
Attaching two json's ([peloton_runs.zip](https://github.com/philosowaffle/peloton-to-garmin/files/3914712/peloton_runs.zip)). Both should also be visible on my Peloton profile.

1. Tread workout: https://members.onepeloton.com/profile/workouts/63eef26a23744af295f14006811b159b
2. Outdoor run (app): https://members.onepeloton.com/profile/workouts/af25d72ea4c0400daeac2707fc30994f

_Note: The outdoor run file includes GPS data. GPS/map doesn't appear on their website, but seems is included in the API, which is great news._

**Comment by clipin** [comment]
While we look to include runs, can we start TCX'ing only workouts we can properly write?

This is probably a useful check to include. As a prereq to TCX'ing non-metric activities like Meditations, which can be TCX'd as "Breathwork". Meditations currently error out, but should be skipped because fail the activity type check, no because missing metrics.

**Comment by philosowaffle** [comment]
I think this has been addressed with #11 .  I included various fixes in that PR, one of which is handling most non-cycling activity types.  Checkout the latest `master` branch and let me know if its still an issue.

**Comment by philosowaffle** [comment]
Just noticed there was sample data attached to an earlier comment. I will test with that.

**Comment by philosowaffle** [comment]
Verified basic support is in place for indoor and outdoor runs. I have logged a separate issue #35 for mapping GPS data as that is more involved and deserves its own ticket.
