### ISSUE TITLE
GPS data for "Just walk/Just run"?

### ISSUE THREAD

**Issue by thorsett** [philosowaffle/peloton-to-garmin#404]
When I do programmed Peloton outdoor runs or walk workouts (e.g., 30 Minute Rock Run with Matty), the gps route data transfers from Peloton to Garmin just fine, but when I use the "Just Work Out" option in the Peloton app and choose outdoor walking or outdoor running, the maps look fine in Peloton but p2g doesn't seem to transfer the gps mapping data to Garmin and I get a workout with no mapping data.

Sorry if this is a known issue, or if I'm just missing some configuration item. I appreciate all the work on this project!

**Comment by philosowaffle** [comment]
If your Peloton profile is public, can you send me a link to one of the workouts you did? I can use that to investigate why the map data isn't getting synced.

**Comment by thorsett** [comment]
I’m WUBearcat on Peloton.  An example is:
https://members.onepeloton.com/profile/workouts/13afceebe0f74a338f60bf9d70f657ef
which becomes this: https://connect.garmin.com/modern/activity/10232384028
at Garmin.

Thanks!

**Comment by philosowaffle** [comment]
This should be fixed now under the 'latest' stream.

**Docker tag**: `latest`
**Windows exe**: https://github.com/philosowaffle/peloton-to-garmin/suites/10178508945/artifacts/497880809
**GH Action**: Sync Fork

**Comment by thorsett** [comment]
Thanks -- that worked.  I very much appreciate your help!
