### ISSUE TITLE
[Feature] WebUI - I'd like to keep track of my progress towards The Annual Challenge

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#406]
On Strava, I can set a goal and it will tell me each day if I am ahead or behind on meeting that goal.  I'd like something similar for the Peloton Annual Challenge.

On the WebUI add a page that shows:
1. All of the tiers available for the Annual Challenge
2. My progress towards each of those tiers
3. Based on the "minutes/day" needed to reach a given tier and where we are in the year, am I ahead or behind on meeting that tier before end of year, and by how much

https://api.onepeloton.com/api/user/9d50dddf7e594c57bda54280eeec98d7/challenges/current?has_joined=false

https://api.onepeloton.com/api/user/9d50dddf7e594c57bda54280eeec98d7/challenge/66863eacd9d04447979d5dba7bf0e766

**Comment by philosowaffle** [comment]
![2023-01-14_11-06-11](https://user-images.githubusercontent.com/7275041/212485652-1b06f40c-bc9e-49e3-96b1-b9513e649b49.png)

**Comment by philosowaffle** [comment]
Couple notes:

1. The challenge seems to have a unique ID but its unclear if this ID would be the same for all users. Current logic will first look for a matching id, then fall back to looking for a Challenge that matches the title "Peloton Annual 2023". This could be brittle logic, will adjust if folks run into issues
2. Lots of assumptions in the code right now about using English and Minutes

Regardless, consider this a usable V1 of this feature. Can iterate more on it if folks use it and have feedback.

**Comment by mattaeus-isenberg** [comment]
Hello! I have tried pulling this into my Docker image, following the docker-compose pull && docker-compose up -d and nothing new is pulled in. the page is still not available.

**Comment by philosowaffle** [comment]
Double check your docker compose file is using the `latest` tag instead of the `stable` tag. ([lines 6 & 18](https://github.com/philosowaffle/peloton-to-garmin/blob/master/docker/webui/docker-compose-ui.yaml))
