### ISSUE TITLE
P2G triggers Garmin password reset

### ISSUE THREAD

**Issue by Lavogel** [philosowaffle/peloton-to-garmin#428]
I installed the docker version of P2G a couple of days ago and everything was working as expected. A few days later I got an e-mail from Garmin telling me I requested a password reset, which I did not. The mail has not been faked but was from Garmin, included a new temporary password and the old one did not work anymore. As I was not sure what caused it, I changed the password at the Garmin website and all connected devices including P2G.

Again everything was working fine for 3 or 4 days but today I got another password reset mail, preventing me to log in with my password set a few days ago. And one hour later I got another one. 
The reason why I blame P2G for this is, that the mails from Garmin were sent the exact minute P2G was syncing. I set my syncing to  every 3600 seconds, so it seems that at every sync a password reset is triggered now.

Is there a Garmin mechanism that prevents logging in too often? Or is this maybe a bug in P2G?

Version: 3.3.1
OS: Unix
OS Version: Unix 4.4.180.0
RunTime Version: 6.0.13

**Comment by philosowaffle** [comment]
This projects official recommendation is for folks to have P2G sync at most once a day.

Setting your sync frequency to 1hr or less can cause you account problems with both Garmin and Peloton.

Related discussion: #359


> Is there a Garmin mechanism that prevents logging in too often? 

Yes, many services employ tactics to catch and prevent bots.
