### ISSUE TITLE
GetTitle WorkerHelper function doesn't properly escape all invalid filename characters (Hint: Don't take the *NSYNC peloton class)

### ISSUE THREAD

**Issue by YakubYo** [philosowaffle/peloton-to-garmin#430]
**Describe the bug**
File IO exception if you take Cody Rigsby's 30 minute *NSYNC class from Nov 2022 and then run Peloton-to-Garmin console app. :) Writing the FIT file locally causes an error.

**To Reproduce**
1. Enjoy cheesy boy-band music while you ride (or choose the class if you've run out of most other options)
2. Run console app
3. Boom

Note:
The issue appears to be that the GetTitle helper function only strips out two of the most common invalid filename characters...

			return $"{rideTitle}{instructorName}"
				.Replace(" ", "_")
				.Replace("/", "-")
				.Replace(":", "-");

Recommend this be replaced with the .NET function to return full set of invalid chars to strip... this worked for me locally:

			string fullTitle = $"{rideTitle}{instructorName}";
			foreach (char invalidChar in Path.GetInvalidFileNameChars())
			{
				fullTitle = fullTitle.Replace(invalidChar, '-');
			}

			return fullTitle.Replace(" ", "_");

Note 1: Running version 3.3.1 of console app on a Windows box
Note 2: Just got this app and otherwise love it! Thanks!

**Comment by philosowaffle** [comment]
Good find, good suggestion.  Day job is killing me right now, but hopefully will have some time to get this fix in on the weekend.

**Comment by YakubYo** [comment]
> Good find, good suggestion. Day job is killing me right now, but hopefully will have some time to get this fix in on the weekend.

Thank for incorporating this fix! This is a fantastic app.
