### ISSUE TITLE
[Feature] Support Device Info replacement for existing tcx files

### ISSUE THREAD

**Issue by garyedwards** [philosowaffle/peloton-to-garmin#451]
I use a Bosch e-cargo bike for my daily commute and generate `tcx` files from the [ebike connect](https://www.bosch-ebike.com/en/connect/) website.  These can be manually uploaded to Garmin connect and viewed without issue.

However these use the `Bosch eBike Connect with barometer` **Device Info** (aka `Creator`) and do not contribute to VO2 Max and TSS as you cover in your [FAQ](https://philosowaffle.github.io/peloton-to-garmin/faq.html).

It would be great if your tool could take these tcx files, swap the Device Info to the peloton-to-garmin's default (TACX App) and upload to Garmin connect.

I appreciate this is probably out of scope for the project given the projects name, but would be really useful for people wanting to get more insights out of their tcx files in Garmin Connect.

**Comment by philosowaffle** [comment]
Does Bosch support exporting FIT files instead of TCX?  If you can get the FIT format, there is an existing online tool that allows you to modify the Device.

https://www.fitfiletools.com/#/changer

**Comment by garyedwards** [comment]
Hi, thanks for the heads up on the fit tool.  Unfortunately the options are:

- GPX
- Strava
- CSV
- TCX

Do you think you could drop an example TACX tcx in this issue and I will try swapping out the appropriate fields in a script?  If I knew C# better I would try to contribute support for Bosch ebikes.

**Comment by garyedwards** [comment]
So it turns out patching the tcx file is relativity easy.  However this file does not make it onto my watch and does not contribute to VO2 Max and TSS even thought the activity shows in Garmin Connect with the correct patched device.

Is this a known issue that only fit files work for VO2 Max and TSS or should tcx files work also?

Thanks for any insights.

**Comment by philosowaffle** [comment]
I'm not aware of any documented limitations between FIT vs. TCX for this data. However, Garmin does have several requirements that need to be met in order for an activity to count towards VO2 max.

**Cycling Requirements**
```
A cycling VO2 max estimate requires that you maintain a steady effort. If you have difficulty obtaining a score, try using an indoor trainer.

    Cycling activity must be 20 minutes or longer without stopping.

    Heart rate data from a built-in optical heart rate sensor or from a chest strap.

    Heart rate must be elevated to at least 70% of your maximum heart rate for at least 20 minutes continuously.

    Power meter is required.

    If using an Indoor Trainer you must record the activity using a Garmin device that supports VO2 Max such as an Edge computer or Forerunner.
```

https://support.garmin.com/en-US/?faq=lWqSVlq3w76z5WoihLy5f8

**Comment by philosowaffle** [comment]
Closing as out of scope for this project.
