### ISSUE TITLE
[strength] Need to re-work how movement tracking + class plan work together

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#453]
Current logic will pull Exercise info from either the MovementTrackerData OR the Class Plan. But the below class demonstrates that they really ought to be used together.... which means we need much more robust mapping logic in P2G.

Movement tracking: https://api.onepeloton.com/api/ride/94826b05633941f3afdb890ab5f35253/details?stream_source=multichannel&include=sampled_top_tags
Class Plan: https://api.onepeloton.com/api/workout/77eb0dff9b4742958203535cd9e98d0f

**Comment by neildsb** [comment]
Hi, not sure if this is related, but I have the following error while pulling a 'Guide' workout when I run the console....PS I am new to your integration and my watch is arriving today (I do not have a watch paired yet) hence I found your solution for joining the platforms. thanks Neil

![image](https://user-images.githubusercontent.com/91122872/228565023-b83e1c7f-15cb-42c1-bed9-0f0ea9b60caa.png)

**Comment by philosowaffle** [comment]
Ah, no this is not related to this particular issue, but it is important.  P2G has to explicitly map every [Peloton Exercise to a Garmin exercise](https://github.com/philosowaffle/peloton-to-garmin/blob/master/src/Conversion/ExerciseMapping.cs#L21). This error message calls out that you preformed some exercises that P2G doesn't yet know how to map.

I just pushed a change that now maps Lateral Raise and Supinated Row, you can download that version [here](https://github.com/philosowaffle/peloton-to-garmin/suites/11902054324/artifacts/622941662).

**Comment by neildsb** [comment]
> Ah, no this is not related to this particular issue, but it is important. P2G has to explicitly map every [Peloton Exercise to a Garmin exercise](https://github.com/philosowaffle/peloton-to-garmin/blob/master/src/Conversion/ExerciseMapping.cs#L21). This error message calls out that you preformed some exercises that P2G doesn't yet know how to map.
> 
> I just pushed a change that now maps Lateral Raise and Supinated Row, you can download that version [here](https://github.com/philosowaffle/peloton-to-garmin/suites/11902054324/artifacts/622941662).

I have started a separate issue thread https://github.com/philosowaffle/peloton-to-garmin/issues/463, not sure if this is annoying for you (would you like me to track this in the other thread?), sorry in advance...I have a few more mapping errors

Reverse Fly
Renegade Row 
Front Raise
Cross Body Curl 
Standing Chest Fly

**Comment by philosowaffle** [comment]
Thanks @neildsb , I don't mind dedicated issues for the Mapping Errors, helps me keep track of which ones I have completed already.

I went ahead and added those exercises to mentioned into 3.5.0-rc version, but haven't had a chance to look into the original bug you logged yet.  Will do that as soon as I get some free time.

**Comment by philosowaffle** [comment]
Windows build: https://github.com/philosowaffle/peloton-to-garmin/suites/12094845929/artifacts/636922537
