### ISSUE TITLE
"No workouts today" on home screen on webui

### ISSUE THREAD

**Issue by manc74** [philosowaffle/peloton-to-garmin#460]
**Describe the bug**
When loading the webui, there is normally a snapshot of the day's workouts along with a button "sync todays workouts". The last few days i just see "No workouts today." and have to click on the sync tab and tick today's workouts manually then the sync button.

**To Reproduce**
1. Go to the webui after finishing a Peloton workout
2. See "No workouts today" on home screen
3. Click "sync" tab, and see todays workouts that can be manually synced.

**Expected behavior**
Seeing a list of todays workouts on the home page and the button to sync them

**Logs**
```
2023-03-29 16:56:35.149 +01:00 [INF] Found 1 workouts remaining after filtering ExcludedWorkoutTypes.
2023-03-29 16:56:35.255 +01:00 [INF] Converting workouts...
2023-03-29 16:56:35.724 +01:00 [INF] Uploading workouts to Garmin...
2023-03-29 16:56:40.399 +01:00 [INF] Uploading to Garmin: /app/working/upload/xxxxxxxxxxxx.fit
2023-03-29 16:56:40.827 +01:00 [INF] Rate limiting, upload will continue after 4 seconds...
2023-03-29 16:56:45.661 +01:00 [INF] Upload complete.

```

**Installation (please complete the following information):**
 - OS: Linux
 - Method: Docker
 - Version: 3.4.1
OS:
Unix
OS Version:
Unix 5.15.0.67
RunTime Version:
6.0.14

**Comment by philosowaffle** [comment]
I've suspected for a bit now that this page has an issue with TimeZones, especially when trying to figure out the start of today.

1. What timezone are you in?
2. Since this issue started happening, was there a change in when you were taking the classes, perhaps significantly earlier or later in the day than normal?

**Comment by manc74** [comment]
Just to update this with a further finding - if I wait an hour or more after completing the workout, it shows up - so it seems to be definitely related to the change from GMT to BST with occurred at the end of March.

**Comment by philosowaffle** [comment]
Closing in favor of #631
