### ISSUE TITLE
no Garmin mapping

### ISSUE THREAD

**Issue by neildsb** [philosowaffle/peloton-to-garmin#472]
My Tuesday Upper Body workouts have found the following mapping errors

P2G Version: p2g_console 3.5.0

Found Peloton Strength exercise with no Garmin mapping: Lawn Mower Row  c80ac3adb6f74487808f361876ba326c
Found Peloton Strength exercise with no Garmin mapping: French Door 78b0a09ce8274e9c8beac6aadd50454b
Found Peloton Strength exercise with no Garmin mapping: High Side Plank a6833a0f9c35489585398d1f293600de
Found Peloton Strength exercise with no Garmin mapping: Boat Pose adbac11d3b714403ba22a175a8c95837
Found Peloton Strength exercise with no Garmin mapping: Scissors  0f9b2d6f18b247bd950d60bbbefd19f3
Found Peloton Strength exercise with no Garmin mapping: Plank Hand Tap ad8e4f16bf5a450db7d3b72b8ff7b014

**Comment by philosowaffle** [comment]
added
