### ISSUE TITLE
Leading 0 in Mfa Code

### ISSUE THREAD

**Issue by jheizer** [philosowaffle/peloton-to-garmin#491]
**Describe the bug**
The HxInputNumber treats the mfa code as an integer and truncates the leading 0.

**To Reproduce**
1. Happen to get a code that has a leading 0.

**Expected behavior**
Treat it as a string instead.

**Logs**
![Screenshot 2023-04-29 10 21 36 PM](https://user-images.githubusercontent.com/1015493/235356157-52d389b8-7759-47cc-966e-1fd27eb04c07.png)

**Installation (please complete the following information):**
 - OS: any
 - Method: any
 - Version: master

**Comment by philosowaffle** [comment]
#492
