### ISSUE TITLE
Mapping issue

### ISSUE THREAD

**Issue by neildsb** [philosowaffle/peloton-to-garmin#495]
P2G Version: p2g_console 3.5.1

Found Peloton Strength exercise with no Garmin mapping: Open Lateral Raise  00046ee377554425866b0a1963b98589
Found Peloton Strength exercise with no Garmin mapping: Pike Push Up 8af39d3485224ac19f7d8659d30524e7

**Comment by philosowaffle** [comment]
Additional exercise from my own logs:

Found Peloton Strength exercise with no Garmin mapping: Dolphin 843d434f59f941c0826fc0fe15eb0236

**Comment by neildsb** [comment]
dolphin, sound painful

**Comment by philosowaffle** [comment]
haha fancy name for what I believe are just Plank Pikes, not too bad.
