### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by neildsb** [philosowaffle/peloton-to-garmin#499]
Hi Phil, just noted you closed the other mapping issue, I have two more :-(

Forearm Side Plank Rotation 223e8e6918d64d9097064d34e3b17e77
Straight Leg Bicycle b617914877c24dac85df81621872e056

**Comment by philosowaffle** [comment]
exercises added :) 

We've got a pretty impressive list of exercises mapped now: b617914877c24dac85df81621872e056
but there will always be more lol
