### ISSUE TITLE
Error when there is a special character in Garmin Password

### ISSUE THREAD

**Issue by pieeaterz** [philosowaffle/peloton-to-garmin#521]
I had a > and a \ in my garmin password.  After experimenting for possible reasons I figured out these (one or both of these) caused the code to crash without error message (ie it never launched the console fully), therefore no error log. Console disappeared very quickly, no error log , so was difficult to intercept.

In the end I changed my Garmin PW to remove these special characters and thereafter the code worked without issue.
 - OS: windows]
 - Method: [exe]
 - Version: [3.5.1]

Console disappeared very quickly, no error log , so was difficult to intercept.

**Comment by philosowaffle** [comment]
Did some testing around this.  Found that most special characters are supported but one exception is the `\` character (json escape character).  I don't see an easy way to add support for this character right now so instead I've opted to explicitly call this out in the documentation.
