### ISSUE TITLE
Sync workflow fails due to omitted false variable in config json

### ISSUE THREAD

**Issue by adepue** [philosowaffle/peloton-to-garmin#534]
Running sync workflow causes causes an invalid config json file if you don't explicitly set save Local to true, as it omits the variable false.  

Started after the merge of: https://github.com/philosowaffle/peloton-to-garmin/pull/532

This error happened to me when running via GH Actions

```
 },
    "Format": {
      "Fit": true,
      "Json": false,
      "Tcx": false,
      "SaveLocalCopy": ,
      "IncludeTimeInHRZones": false,
      "IncludeTimeInPowerZones": false,
      "DeviceInfoPath": "./deviceInfo.xml"
    },
    "Peloton": {
```

Additionally, once setting to true, the output fails to save with a path character error:
```
Artifact path is not valid: /c46871a40e964879bf32d9c7055d7786_Extra_10:_Low_Impact_Ride_with_Matt_Wilpers.fit. Contains the following character: Colon : Invalid characters include: Double quote 
``` 
Haven't had a chance to look into it further yet, but noting here incase anyone happens to run into it or has immediate ideas.

**Comment by anlesk** [comment]
1. The "false" default issue is coming from the cron trigger - it does not respect the default input.
Thus, it have to be set up explicitly. I'll make a PR shortly.
2. For filename, this is interesting, as looks like the rules for filenames are different for upload artifact and OS running the action. I'll check later today the specs for that action.

**Comment by anlesk** [comment]
The workaround would be to pre-zip files and upload zip archive as mentioned here: https://github.com/actions/upload-artifact/issues/333#issuecomment-1227464293

**Comment by philosowaffle** [comment]
Fix merged for handling issue 1.
Re-opened since fix for issue 2 is still in the works.

**Comment by philosowaffle** [comment]
Thank you @anlesk for the new capability and quick fixes!

**Comment by adepue** [comment]
Thanks for the quick fixes!!
