### ISSUE TITLE
[Feature] Add option to Exclude OutdoorCycling

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#559]
### Discussed in https://github.com/philosowaffle/peloton-to-garmin/discussions/558

<div type='discussions-op-text'>

<sup>Originally posted by **Buccafresh** November 11, 2023</sup>
Hi there, 

I was wondering if it is possible to exclude "Just Ride Outdoors" / Outdoor cycling when using this amazing tool to sync from Peloton to Garmin. Currently, I saw these were the available options below. However, I am noticing my sync is double-counting the "Just Ride Outdoors" that I do in the Peloton App on my Android phone. (I record my outside bike rides with my Garmin watch, but also the Peloton app on my phone to get the badges/peloton challenges, even though I prefer the interface on my Garmin watch much more. I start my phone, and toss it in my riding backpack.) Is it possible to add "OutdoorCycling" to the code?

**_My research from the published wiki_**

Exclude Workout Types
Example use cases:

You take a wide variety of Peloton classes, including meditation and you want to skip uploading meditation classes.
You want to avoid double-counting activities you already track directly on a Garmin device, such as outdoor running workouts.
The available values are:

  Cycling
  BikeBootcamp
  TreadmillRunning
  OutdoorRunning
  TreadmillWalking
  OutdoorWalking
  Cardio
  Circuit
  Strength
  Stretching
  Yoga
  Meditation

Please add **OutdoorCycling** If it's technically possible.</div>

**Comment by philosowaffle** [comment]
@Buccafresh I've got some time to work on this but I will need a sample workout to see how Peloton identifies `Outdoor Cycling` workouts at the data level.

If you have an example workout on Peloton, could you please temporarily friend me `@cyclesaurus` on Peloton?  This will let me view your workouts and I'll be able to inspect the Outdoor Cycling activity you did to see how P2G could identify it.  Once I've got that figured out you can un-friend me.

**Comment by Buccafresh** [comment]
Absolutely, I just added you! TheLitStopSign is my name. If you look at my
workouts, you will see two rides on 12/18/2023. If you look my first ride
at 2:30 with 25.88 miles has more correct data than the one at 5:20 where I
accidentally paused my phone and restarted later (hense the straight line
on that map.)

Best,

Joe

**Comment by philosowaffle** [comment]
Thank you! Got the info I needed, feel free to un-follow me.  This new option will be available in the next v4.1.0 release.

**Comment by Buccafresh** [comment]
Thank you for your implementation of this in v4.1.0's release! I downloaded it on Windows. Can I ask if "excluding workout types" is also available on GitHub actions? I didn't see the line of code after peloton in the sync_peloton_to_garmin.yml file that would allow me to specify it.

**Comment by philosowaffle** [comment]
[Here's an example](https://github.com/gunjanmarwah/peloton-to-garmin/blob/master/.github/workflows/sync_peloton_to_garmin.yml#L54) of how to set it (from another users gha setup).

**Comment by Buccafresh** [comment]
Thank you very much! Got that to work with your helpful code line example. I find Github is helpful when I am not around a computer, I can go on my cellphone and sync the workouts from the desktop site in google chrome. I also downloaded their mobile app for Android, but I can't seem to find the "sync workflow" button on the mobile app. Do you know if this is a possibility? 

Also - Git hub uploaded a weird title on my chest and back strength in Garmin it called it Chest &amp; back strength. I was able to manually fix it in Garmin, but I wanted to report this just in case it was a bug!
