### ISSUE TITLE
"Workout already uploaded to Garmin", but I deleted all workouts after changing the "upload enabled=true"

### ISSUE THREAD

**Issue by mkgraham82** [philosowaffle/peloton-to-garmin#60]
I have to say great thing you are doing here! Thanks so much!!

I wanted to upload all 287 rides from peloton to Garmin Connect.
I first did it manually, I noticed that the workout title is "Cycling" however when uploaded is enabled for automatically upload to Garmin, the Peloton class title is listed, like "**Top 50 of 2020 (#40 - 31) with Leanne Hainsby**"
Also a manual upload shows '**Cycling**' compared to automatic upload as "**Indoor Cycling**"

I did not notice the "upload enabled" option until I manually uploaded the 287 rides.   I then deleted all of them from Garmin connect and now tried around 30 and it keeps saying "**Workout already uploaded to Garmin**"

**Comment by philosowaffle** [comment]
Hello! If you look in the directory where you downloaded this tool, you should see a file named `database.json`. You can safely delete this file. It keeps track of workouts that have already been uploaded so that duplicates are not sent to Garmin.

Delete this file, then re-run the tool and it should send them all to Garmin.

**Comment by philosowaffle** [comment]
For the curious, when uploading a TCX file manually, Garmin does not honor the activity name and it also only supports a small set of activity types (run, bike, and other).  The automated upload process in this tool takes advantage of the "unofficial" Garmin api which has some additional features such as setting the workout title and additional activity types.

**Comment by mkgraham82** [comment]
> Hello! If you look in the directory where you downloaded this tool, you should see a file named `database.json`. You can safely delete this file. It keeps track of workouts that have already been uploaded so that duplicates are not sent to Garmin.
> 
> Delete this file, then re-run the tool and it should send them all to Garmin.

Thanks so much! It worked.  Enjoy your coffee I sent the other day!

**Comment by mkgraham82** [comment]
I think my issue is fixed!

Ride on!
