### ISSUE TITLE
performance_graph endpoint 'every_n=1' stopped working?

### ISSUE THREAD

**Issue by RJHug00** [philosowaffle/peloton-to-garmin#618]
The performance_graph endpoint query argument 'every_n=1' seems to have recently stopped reliably returning data for each second of a ride. It used to work.  I haven't tried to see if 'every_n=2' or 'every_n=10' works, which might suggest there being a new or different query argument now, but I did try 'every_n=0' and got the same return as 'every_n=1'.

Just today, I ran a query that had been working fine for way over a year, but this time, the return array of 'seconds_since_pedaling_start' has numerous gaps, e.g. [2, 3, 5, 6, 7, 9, ...], where it previously always contained [1, 2, 3, 4, 5, ...] for the number of seconds of the workout.  The final integer in the array is indeed the same as the 'duration' element says it should be (i.e. both are 1200 for a 20-minute ride).

Just wondering if you've heard anything from your users or from Peloton to explain this new behavior.  I'm mostly sending this message to alert you that complaints along these lines may start flowing your way.

It has been a few weeks since the Peloton Bike+ software updated, but I've done several rides and queries since then without issue, and I'm wondering if that is where the actual underlying problem originates (i.e. not capturing every second for some reason).

[just whip this issue into oblivion after you read it]

Best wishes and good luck.
-Randy

**Comment by RJHug00** [comment]
Additional research reveals the observed 'problem' may be limited to the one ride, or more likely that 'type' of ride as it was captured.  A [warmup] ride immediately prior and a [cooldown] ride immediately after do not exhibit the sampling gaps.  The particular ride in question happened to be Peloton's 20-minute FTP test, making it seem like the bike was told to capture data by some method other than sample-per-second for that workout.  Still interesting to keep on the periphery of your radar.

**Comment by philosowaffle** [comment]
hmmm This is interesting, I haven't heard any other reports of this (yet) but I'll definitely keep any eye out. Thank you or sharing!
