### ISSUE TITLE
Unable to connect to Garmin API (credentials are correct)

### ISSUE THREAD

**Issue by stando76** [philosowaffle/peloton-to-garmin#63]
This started about a week ago - I have confirmed that the credentials are correct.

![image](https://user-images.githubusercontent.com/50504474/104199505-88ac0580-53f5-11eb-858d-45a7601c09bc.png)

**Comment by philosowaffle** [comment]
Duplicate of: https://github.com/philosowaffle/peloton-to-garmin/issues/62

Please see towards the end of the thread for more information.
