### ISSUE TITLE
Update Docker Image

### ISSUE THREAD

**Issue by ryanmac8** [philosowaffle/peloton-to-garmin#65]
Please update the docker image to use the new python requirements as my Garmin authenticating is failing and it seems like the docker image hasn't been updated to pull in the new requirements that were released to fix the issue.

**Comment by philosowaffle** [comment]
ping @Octopusprime83

I think @mhjansen79 has also volunteered to help out with maintaining the image in the future if they can have the know-how and access to do so.

**Comment by ryanmac8** [comment]
Thanks @philosowaffle.

@Octopusprime83 Can you let us know what's going on with the docker image. Is there a separate GitHub for the dockerfile or where we should file issues? Also if you are no longer maintaining the image, please let me know.

**Comment by philosowaffle** [comment]
I'm sorry this is still sitting open y'all.  Unfortunately, my dev environment at home is not setup in a way that makes it easy for me to work with or maintain docker containers, otherwise I would help out.

**Comment by mhjansen79** [comment]
No worries. I’m working backwards from the existing container to see if i can do it myself and then help you maintain it in the future.

**Comment by ryanmac8** [comment]
I was able to get the dockerfile from the old container and update it. It looks like the docker version has custom code to take in environment variables. I started to work on a container that just takes the python script from the repo and builds a container without modifying it. If that's of interest to anybody, I can make it public.

**Comment by Octopusprime83** [comment]
This container was updated on 1/20 to the latest code available from this Git repo. I tested it in the docker container and it appeared to be signing on to docker for me to I pushed to the repo. If you guys want to take it over then feel free.

**Comment by mhjansen79** [comment]
> I was able to get the dockerfile from the old container and update it. It looks like the docker version has custom code to take in environment variables. I started to work on a container that just takes the python script from the repo and builds a container without modifying the python script. If that's of interest to anybody, I can make it public.

sounds linke the most robust solution for the future.

**Comment by anlesk** [comment]
@ryanmac8 
Yep, would be great to have the dockerfile somewhere in public, so we can modify one if necessary.
The latest one on the docker hub doesn't seem to work for me.

@Octopusprime83 can you share the dockerfile?

**Comment by Octopusprime83** [comment]
@anlesk on this gut to back a couple revisions and the docker file will be present in the master downlownload this is the one I've been using. As for the rest I remove the pelo and Garmin logins from the config.ini file, as the environment variables will be passed when the container is created. As for the main python script, I then go in and add repoint the script from the config. Ini to the environmental variables needed. Then the main script gets copied within the python script to either wait and loop back or quit based on how the debug variable is set. I can share this but I'm no python programmer so I'm sure there's a more elegant way to do this.

**Comment by philosowaffle** [comment]
Original docker file: https://github.com/philosowaffle/peloton-to-garmin/blob/209056f1b7ec04e6d058c07f5e48866a35c0b590/dockerfile

@Octopusprime83  if you want to submit a pr with your looping and environment variable changes I will take a look at it and clean it up (if needed).  Seems like integrating those changes to the code would make it much easier to maintain the docker container going forward.

**Comment by Octopusprime83** [comment]
Will do, currently in the process of moving my entire home networking set up into the confines of a server cabinet. Once I'm back up and running I'll send it over.

**Comment by ryanmac8** [comment]
I submitted a PR for environment variable support and once that has been committed, I can get a dockerfile created.

**Comment by philosowaffle** [comment]
@ryanmac8 pr has been merged to master. Is master good enough for now or do you need a release cut?

**Comment by ryanmac8** [comment]
Master is fine.

**Comment by ryanmac8** [comment]
> @ryanmac8 pr has been merged to master. Is master good enough for now or do you need a release cut?

Master is fine.

**Comment by q20** [comment]
Sooooo, does this mean a new docker file is in the wings?  ; )

**Comment by Octopusprime83** [comment]
I have finally got my computer back up and running, sorry for the delay (parts came from china). Here is an example of the modifications I make to the peloton-to-docker.py file I import a few more things at the top and then alter where the email and password elements are being pulled from in the code itself.


`#
# Author: Bailey Belvis (https://github.com/philosowaffle)
#
# Tool to generate a valid TCX file from a Peloton activity for Garmin.
#
import argparse
import json
import logging
import urllib3
import os
import time

from lib import configuration
from lib import pelotonApi
from lib import tcx_builder
from lib import garminClient
from tinydb import TinyDB, Query
from datetime import datetime

##############################
# Main
##############################
class PelotonToGarmin:
    
    @staticmethod
    def run(config):
        numActivities = config.numActivities
        logger = config.logger
        pelotonClient = pelotonApi.PelotonApi(os.environ['PELO_EMAIL'], os.environ['PELO_PASS'])
        database = TinyDB('database.json')
        garminUploadHistoryTable = database.table('garminUploadHistory')
        debug = os.environ['DEBUG']

        while debug == "false":
            if numActivities is None:
                numActivities = input("How many past activities do you want to grab?  ")

            logger.info("Get latest " + str(numActivities) + " workouts.")
            workouts = pelotonClient.getXWorkouts(numActivities)

            if config.uploadToGarmin:
                garminUploader = garminClient.GarminClient(os.environ['GARM_EMAIL'], os.environ['GARM_PASS'])
        
            for w in workouts:
                workoutId = w["id"]
                logger.info("Get workout: {}".format(str(workoutId)))

                if w["status"] != "COMPLETE":
                    logger.info("Workout status: {} - skipping".format(w["status"]))
                    continue

                workout = pelotonClient.getWorkoutById(workoutId)

                logger.info("Get workout samples")
                workoutSamples = pelotonClient.getWorkoutSamplesById(workoutId)

                logger.info("Get workout summary")
                workoutSummary = pelotonClient.getWorkoutSummaryById(workoutId)

                try:
                    title, filename, garmin_activity_type = tcx_builder.workoutSamplesToTCX(workout, workoutSummary, workoutSamples, config.output_directory)
                    logger.info("Writing TCX file: " + filename)
                except Exception as e:
                    logger.error("Failed to write TCX file for workout {} - Exception: {}".format(workoutId, e))

                if config.uploadToGarmin:
                    try:
                        uploadItem = Query()
                        workoutAlreadyUploaded = garminUploadHistoryTable.contains(uploadItem.workoutId == workoutId)
                        if workoutAlreadyUploaded:
                            logger.info("Workout already uploaded to garmin, skipping...")
                            continue

                        logger.info("Queing activity for upload: {}".format(title))
                        fileToUpload = config.output_directory + "/" + filename
                        garminUploader.addActivity(fileToUpload, garmin_activity_type.lower(), title, workoutId)
                    except Exception as e:
                        logger.error("Failed to queue activity for Garmin upload: {}".format(e))

            if config.uploadToGarmin:
                try:
                    logger.info("Uploading activities to Garmin...")
                    garminUploader.uploadToGarmin(garminUploadHistoryTable)
                except Exception as e:
                    database.close()
                    raise e

            logger.info("Done!")
            logger.info("Your Garmin TCX files can be found in the Output directory: " + config.output_directory)
            logger.info("Check Complete, will recheck in 10 min.")
            time.sleep(600)

        while debug == "true":
        
            if numActivities is None:
                numActivities = input("How many past activities do you want to grab?  ")

            logger.info("Get latest " + str(numActivities) + " workouts.")
            workouts = pelotonClient.getXWorkouts(numActivities)

            if config.uploadToGarmin:
                garminUploader = garminClient.GarminClient(os.environ['GARM_EMAIL'], os.environ['GARM_PASS'])
        
            for w in workouts:
                workoutId = w["id"]
                logger.info("Get workout: {}".format(str(workoutId)))

                if w["status"] != "COMPLETE":
                    logger.info("Workout status: {} - skipping".format(w["status"]))
                    continue

                workout = pelotonClient.getWorkoutById(workoutId)

                logger.info("Get workout samples")
                workoutSamples = pelotonClient.getWorkoutSamplesById(workoutId)

                logger.info("Get workout summary")
                workoutSummary = pelotonClient.getWorkoutSummaryById(workoutId)

                try:
                    title, filename, garmin_activity_type = tcx_builder.workoutSamplesToTCX(workout, workoutSummary, workoutSamples, config.output_directory)
                    logger.info("Writing TCX file: " + filename)
                except Exception as e:
                    logger.error("Failed to write TCX file for workout {} - Exception: {}".format(workoutId, e))

                if config.uploadToGarmin:
                    try:
                        uploadItem = Query()
                        workoutAlreadyUploaded = garminUploadHistoryTable.contains(uploadItem.workoutId == workoutId)
                        if workoutAlreadyUploaded:
                            logger.info("Workout already uploaded to garmin, skipping...")
                            continue

                        logger.info("Queing activity for upload: {}".format(title))
                        fileToUpload = config.output_directory + "/" + filename
                        garminUploader.addActivity(fileToUpload, garmin_activity_type.lower(), title, workoutId)
                    except Exception as e:
                        logger.error("Failed to queue activity for Garmin upload: {}".format(e))

            if config.uploadToGarmin:
                try:
                    logger.info("Uploading activities to Garmin...")
                    garminUploader.uploadToGarmin(garminUploadHistoryTable)
                except Exception as e:
                    database.close()
                    raise e

            logger.info("Done!")
            logger.info("Your Garmin TCX files can be found in the Output directory: " + config.output_directory)
            logger.info("Debug mode enabled, exiting code...")
            break

##############################
# Program Starts Here
##############################
if __name__ == "__main__":
    config = configuration.Configuration(argparse.ArgumentParser())
    PelotonToGarmin.run(config)`

**Comment by philosowaffle** [comment]
@Octopusprime83 , @ryanmac8 , and other Docker folks, added basic support for polling to the master branch: https://github.com/philosowaffle/peloton-to-garmin/pull/72

Also cleaned up the configuration documentation.  I think y'all should have everything you need now to minimize work in maintaining a docker container going forward. 

https://github.com/philosowaffle/peloton-to-garmin#configuration

**Comment by philosowaffle** [comment]
So I made some docker images: https://github.com/philosowaffle/peloton-to-garmin#docker

But I'm having trouble getting any of them to work on my raspberrypi 4 (suspect os architecture issue). Anyone else willing to test them out and see if they are working?

**Comment by philosowaffle** [comment]
Ok, I am now fairly sure I've got a docker image published that works.  Links and sample compose file can be found here:

https://github.com/philosowaffle/peloton-to-garmin#docker

Going to go ahead and close this issue for now. We can open a new, more specific issue if any problems arise.

**Comment by mhjansen79** [comment]
For me it works great @philosowaffle  thanks for this! For other users, one thing I did need to do extra compared with the previous container is to add a reference to the log folder. After that it runs perfect.
