### ISSUE TITLE
Latest update still shows update available

### ISSUE THREAD

**Issue by manc74** [philosowaffle/peloton-to-garmin#655]
**Describe the bug**
Updated to latest docker image (stable tag), shows v4.20-rc instead of v4.20 so still shows an update available

**Installation (please complete the following information):**
 - OS: [linux]
 - Method: [docker]
 - Version: [4.20, dockerTag, stable]

**Additional context**
![Screenshot_20240815_220447_Chrome](https://github.com/user-attachments/assets/ff771d51-8257-452f-909a-31e1be56d544)

**Comment by philosowaffle** [comment]
Might have fixed it, try pulling latest again now.

**Comment by manc74** [comment]
Still the same unfortunately.  Changed from stable to latest for both api and website and still shows rc.

**Comment by sidens** [comment]
Same issue here - following!

**Comment by geoffbon** [comment]
This looks good to me now in 4.3.0, running docker web UI.
