### ISSUE TITLE
[Feature] Elevation on Runs

### ISSUE THREAD

**Issue by milleruk** [philosowaffle/peloton-to-garmin#668]
**Is your feature request related to a problem? Please describe.**
Grab the elevation from a Tread workout so that it maps to Garmin - Happy for you to use my profile again as with the Guide metrics 

**Describe the solution you'd like**
Elevation is added so that The Total Ascent is shown in Garmin

**Comment by philosowaffle** [comment]
Also related to #415

**Comment by philosowaffle** [comment]
closing as duplicate of #476 - on the roadmap
