### ISSUE TITLE
":" in workout title causes file creation failure

### ISSUE THREAD

**Issue by clipin** [philosowaffle/peloton-to-garmin#8]
When a colon (":") exists in workout title (see "[15 min Move for More: Climb Ride](https://members.onepeloton.com/profile/workouts/be0ddcde3da141a1bfa5636fbb28937d?modal=classDetailsModal&classId=06149fb785ed4c569fb62705587bae7a)") it causes python parser to fail w/o throwing error in terminal. An empty file is created, no extension and filename stops at point of colon.

Example workout: [json](https://api.onepeloton.com/api/workout/be0ddcde3da141a1bfa5636fbb28937d). Issued is caused in tcx_builder.py at line 205 `workout["ride"]["title"]`. I worked around by changing `title` to `rating`, but not a long-term fix.

**Comment by philosowaffle** [comment]
Give this branch a go and let me know if it resolves the issue:

Branch: `issue/8`
PR: https://github.com/philosowaffle/peloton-to-garmin/pull/9

**Comment by clipin** [comment]
Perfect, works ty!
