### ISSUE TITLE
Not counting towards badges.

### ISSUE THREAD

**Issue by kenlpeters** [philosowaffle/peloton-to-garmin#86]
I am not sure this old or new, Since I started using this process after my March Badges were complete.  But it appears that the Peloton activity (Walk and Cycling) did not get counted towards my badges for Garmin.  Is this normal and is there anything we can do to fix this.  I guess I could start the process on my watch and then manually enter the mileage afterward.  Just seems redundant.

**Comment by kenlpeters** [comment]
I was able to fix this myself with a few modifications.

1)   I downloaded a TCX from garmin where I used my device.
2)   Create device.info and copy the creator tag from the TCX and paste into the device.info. Example below.
      <Creator xsi:type="Device_t">
        <Name>Venu</Name>
        <UnitId>3353549671</UnitId>
        <ProductID>3226</ProductID>
        <Version>
          <VersionMajor>5</VersionMajor>
          <VersionMinor>60</VersionMinor>
          <BuildMajor>0</BuildMajor>
          <BuildMinor>0</BuildMinor>
        </Version>
      </Creator>
3)  Create a author,info file and copy the author tag into that file.  Example:
  <Author xsi:type="Application_t">
    <Name>Connect Api</Name>
    <Build>
      <Version>
        <VersionMajor>0</VersionMajor>
        <VersionMinor>0</VersionMinor>
        <BuildMajor>0</BuildMajor>
        <BuildMinor>0</BuildMinor>
      </Version>
    </Build>
    <LangID>en</LangID>
    <PartNumber>006-D2449-00</PartNumber>
  </Author>
4)  Modified Peloton-To-Garmin.py to include this code
with open("device.info","r") as file:
deviceinfo = file.read()

with open("author.info","r") as file:
authorinfo = file.read()

with open(config.output_directory+"/"+ filename,"r") as file:
filedata = file.read()

filedata.replace("</Activity>", deviceinfo + "</Activity>")
filedata.replace("</TrainingCenterDatabase>", authorinfo + "</TrainingCenterDatabase>")

with open(config.output_directory+"/"+ filename,"w") as file:
file.write(filedata)

5) Delete the database.json
6) Delete files from Output
7) Run import again.

I am sure there is better way to do this but it worked for me.

**Comment by kenlpeters** [comment]
I included the code for the py file in my PR.  I did not attach the device.info or author.info as this will be different per user once they download and copy the information from the garmin TCX file.

**Comment by RicardoNiepel** [comment]
Awesome - I will test it!

**Comment by RicardoNiepel** [comment]
Link #86

**Comment by kenlpeters** [comment]
I have been using this for weeks now and everything is performing perfectly.
